### ISSUE TITLE
Update to GeoBlacklight v4.4

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1044]
This release comes with a couple of notable changes (see the [release notes on github](https://github.com/geoblacklight/geoblacklight/releases/tag/v4.4.0.rc1)):

- Vite is now used to bundle JS dependencies. We probably want to adopt this more modern tooling too
- There is built-in support for COG (part of #867) and PMTiles viewing via Leaflet
- The new Clover viewer is provided for IIIF items (we may want to stick with Mirador for consistency?)
- A "copy to clipboard" feature is added to the web services modal, which is a nice UI thing

If supporting Vite for JS bundling requires a lot more extra work, perhaps another ticket should be spun off from this one.

**Comment by jcoyne** [comment]
See related #1061

**Comment by thatbudakguy** [comment]
superseded by other tickets since we're going straight to v5
