### ISSUE TITLE
Use more specific icons for layers where possible

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1045]
**Note**: this could be accomplished in GeoBlacklight, or drafted in Earthworks and then ported to GeoBlacklight later. See related issue https://github.com/geoblacklight/geoblacklight/issues/1041.

# The problem

In GeoBlacklight v3, there was a [simple single-valued field](https://opengeometadata.org/1.0-geometry-type/#geometry-type) for tracking the "geometry type" of a layer that determined what icon to use. This helped distinguish between e.g. polygon data and point data:

![Screenshot 2024-06-07 at 10 04 42 AM](https://github.com/sul-dlss/earthworks/assets/4924494/4f6e725a-91cd-4e40-998f-1f3b841d9249)

In GeoBlacklight v4, there are two fields that describe the type of a layer, and both are multi-valued: the more general [resource class](https://opengeometadata.org/ogm-aardvark/#resource-class) and more specific [resource type](https://opengeometadata.org/ogm-aardvark/#resource-type). Both have controlled vocabularies; note that resource type actually has two separate controlled vocabularies (one for maps and one for geo data).

The current implementation just uses the first value from resource class to decide what icon to use. This means all geo data is lumped into one "Datasets" category, so an index map appears no different from a raster:

![Screenshot 2024-06-07 at 10 08 13 AM](https://github.com/sul-dlss/earthworks/assets/4924494/301ebcc0-189a-4f34-bdfa-ed0a41dab4ac)

Similarly, when looking at the relation box on collection pages, all of the members of the collection use a generic "leaf" icon instead of the one that indicates what data type they are:

![Screenshot 2024-06-07 at 10 37 46 AM](https://github.com/sul-dlss/earthworks/assets/4924494/0eb2d246-233e-4caf-ad96-0b1199753b98)

Ideally, we could get some of the old behavior back, where things like polygon data and line data are distinguished.

# Implementation ideas

- if the item has a resource class of "Collections", "Maps", "Other", etc. just use the current behavior.
- if the item has a resource class of "Datasets", we need to look at the resource type.
  - "Polygon data" -> polygon icon
  - "Line data" -> line icon
  - "Point data" -> point icon
  - "Raster data" -> raster icon
  - other stuff...see what's available in GeoBlacklight?

# Places to look

- the [`header_icons`](https://github.com/geoblacklight/geoblacklight/blob/v4.4.0.rc1/app/views/catalog/_header_icons.html.erb) partial is responsible for rendering the three icons per record (lock, institution icon, and layer type icon)
- the [`geoblacklight_helper`](https://github.com/geoblacklight/geoblacklight/blob/afdacadd0d10be060f396e08c966c42b95a6835e/app/helpers/geoblacklight_helper.rb#L76-L89) is ultimately what gets called to get an icon or use a default if it can't find one
- there is a setting called [`RELATIONSHIPS_SHOWN`](https://github.com/geoblacklight/geoblacklight/blob/afdacadd0d10be060f396e08c966c42b95a6835e/lib/generators/geoblacklight/templates/settings.yml#L144-L145) that determines how the relationships sidebar/box gets rendered; this determines what icon is used when e.g. looking at the listing of items in a collection on the collection's page.
- to get resource type information available at the time we render those relationship sidebars (and thus display a specific icon and not the generic "leaf" or "collection" icon), we would need to update/override the relevant relation response classes, like [`Ancestor`](https://github.com/geoblacklight/geoblacklight/blob/afdacadd0d10be060f396e08c966c42b95a6835e/lib/geoblacklight/relation/ancestors.rb#L12-L15), so that we ask solr to return that field in the relation query. then we can use it to render the icon. (this is what the setting [`USE_GEOM_FOR_RELATIONS_ICON`](https://github.com/geoblacklight/geoblacklight/blob/afdacadd0d10be060f396e08c966c42b95a6835e/lib/generators/geoblacklight/templates/settings.yml#L106-L107) did in gblv3, but it's broken in v4).

**Comment by dnoneill** [comment]
https://github.com/geoblacklight/geoblacklight/pull/1391 closes #1045

**Comment by marlo-longley** [comment]
Handled upstream.
