### ISSUE TITLE
Add autogenerated code samples for using layers

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1049]
You can view this prototype by visiting the [interactive prototype](https://www.figma.com/proto/nkgg905s5FyXoyPZjVMco0/EarthWorks?page-id=0%3A1&node-id=89-2697&viewport=-3973%2C-836%2C0.58&t=5oPw70wWwebL9uPW-1&scaling=min-zoom&starting-point-node-id=9%3A148&show-proto-sidebar=1), visiting a layer detail page, and clicking "code samples" in the tools panel.

This deserves a little bit of thought with regard to maintainability: do we just have the code samples as string templates that get the layer ID, etc. injected into them? Do we do any work to validate that the code still runs/is up to date? Can they be tested? etc.

If directly writing out the code isn't the best way, perhaps step-by-step instructions or links would still be helpful. @mapninja is a good person to ask about how this will be used in practice (e.g. by students).

**Comment by thatbudakguy** [comment]
See #910 for details on the code snippets.

**Comment by hudajkhan** [comment]
Authorization has its own issue: #1093

**Comment by hudajkhan** [comment]
Moving this back to in progress because need to generate a new pull request based on the BL8 branch instead.

**Comment by marlo-longley** [comment]
Remove code snippets on restricted datasets re: https://github.com/sul-dlss/earthworks/issues/1093

**Comment by hudajkhan** [comment]
Closed by #1125
