### ISSUE TITLE
Audit the site with SiteImprove

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1051]
Prelude to asking for detailed review from SODA; we want to handle as much as we can ourselves before asking.

The site is already available in the dashboard, but we may need to poke SiteImprove or run the audit manually after all of our UI updates. We also need to ticket any identified issues (A or AA).

**Comment by marlo-longley** [comment]
Decision: we will run this on Monday August 26.

**Comment by dbranchini** [comment]
Done and added issues with "Accessibility" label.
