### ISSUE TITLE
Update the header

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1053]
See [the interactive prototype](https://www.figma.com/proto/nkgg905s5FyXoyPZjVMco0/EarthWorks?page-id=0%3A1&node-id=190-4386&viewport=-3973%2C-836%2C0.58&t=g6nuKFbuALQqwBG7-1&scaling=min-zoom&starting-point-node-id=190%3A4386&show-proto-sidebar=1).

This work was done recently in stanford-arclight, e.g. https://github.com/sul-dlss/stanford-arclight/blob/main/app/views/shared/_stanford_stripe.erb

**Comment by thatbudakguy** [comment]
See also the reference implementation (if it's ready?) in https://github.com/sul-dlss/component-library

**Comment by jcoyne** [comment]
Possibly depends on https://github.com/sul-dlss/earthworks/issues/1063

**Comment by dbranchini** [comment]
Note the mobile menu in Arclight (which splits the header to display the menu) is not the final or what DLUX decided on. It should display the navigation below the EarthWorks title as seen here - 

https://www.figma.com/proto/nkgg905s5FyXoyPZjVMco0/EarthWorks?page-id=0%3A1&node-id=335-15305&viewport=-7294%2C1192%2C0.56&t=kYki5n8Z1jZKPmeu-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=335%3A15305
