### ISSUE TITLE
Switch from sprockets to jsbundling-rails

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/earthworks#1061]

**Comment by thatbudakguy** [comment]
Based on the work I've been doing recently in geoblacklight, I think we will have to use vite. It could be possible to re-add support for other bundling strategies to geoblacklight, but I don't know enough about how to do it yet.

**Comment by thatbudakguy** [comment]
We're using importmaps now in the `bl8` branch and it's working, so closing this.
