### ISSUE TITLE
Raster image doesn't support feature inspection

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1080]
For https://earthworks.stanford.edu/catalog/stanford-qz033pg4379, if you click in the viewer...nothing happens? Unclear why this is true of that record but not e.g. https://earthworks.stanford.edu/catalog/stanford-pc204zy5923, another georeferenced raster that does support inspection. Possibly a bug, maybe a data problem?

**Comment by dnoneill** [comment]
Looks to be a data problem. When we query

**Comment by dnoneill** [comment]
Looks to be a data problem. The data coming from the wms server for qz033pg4379 and qh711pf3383 return 
```
{"version":"1.1.1","exceptions":[{"code":"OperationNotSupported","locator":"QUERY_LAYERS","text":"Either no layer was queryable, or no layers were specified using QUERY_LAYERS"}]}
```

However, [mr099qm5693](https://purl.stanford.edu/mr099qm5693) which is in a similar format works perfectly.

**Comment by thatbudakguy** [comment]
Pending some data investigation by @kimdurante.

**Comment by thatbudakguy** [comment]
Sounds like the work here is now to investigate whether we can find and programmatically enable the "Queryable" state for all our raster layers.

**Comment by kimdurante** [comment]
I have set all layers on both the public and restricted GeoServers as 'Queryable.' The queryable property can either be True or False. 
There is probably something in the GIS Delivery robots that needs to be updated to always be True, unless there is some reason why we wouldn't want this (I can't think of any).

**Comment by peetucket** [comment]
see https://github.com/sul-dlss/gis-robot-suite/pull/911#issuecomment-2251549090 for some comments on a potential fix I have that may require some more testing
