### ISSUE TITLE
Stop harvesting restricted records from OpenGeoMetadata institutions

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1089]
The original purpose for this was to account for cases where someone saw a record that another institution held privately and could tell us they wanted us to buy it, but it sounds like this doesn't really happen (anymore). That being the case, there's little that our users can do with this data, so we may as well not index it at all.

Earthworks subclasses GeoCombine's harvester to add some behavior that lets us skip arbitrary records; this would probably be the easiest place to check if the record is restricted:
https://github.com/sul-dlss/earthworks/blob/7b59ee73f8b1a0f39244f01b9d3fc972bde66218/lib/earthworks/harvester.rb#L26-L32

Then we just need to clear out non-Stanford records from the index and re-run the OGM indexing job. That job is defined here:
https://github.com/sul-dlss/earthworks/blob/7b59ee73f8b1a0f39244f01b9d3fc972bde66218/config/schedule.rb#L50-L53

**Comment by thatbudakguy** [comment]
Calling this completed since the remaining work is a full reindex, which doesn't necessitate code changes.

**Comment by jmartin-sul** [comment]
> Calling this completed since the remaining work is a full reindex, which doesn't necessitate code changes.

thanks!  wasn't sure whether the ticket was supposed to stay open till that was done.
