### ISSUE TITLE
Deal with lobsters

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/earthworks#1091]
The synonyms file for LCSH mappings from OpenGeoPortal equates "invertebrates" with lobsters and mosquitoes by putting all these words on the same line and separating with commas.  

We could address this issue by changing these lines to more carefully provide additional terms for query expansion. 
For example:

- invertebrates => lobsters, mosquitoes.  This would take a query that has the word "invertebrates" and add both "lobsters" and "mosquitoes" to the query.

**Comment by hudajkhan** [comment]
Will affect #41

**Comment by peetucket** [comment]
![Image](https://github.com/user-attachments/assets/be78deeb-34fa-451d-901b-c53d841363e4)

**Comment by hudajkhan** [comment]
Lobsters have been dealt with: 
https://github.com/sul-dlss/earthworks/pull/1083
and
https://github.com/sul-dlss/sul-solr-configs/pull/334
