### ISSUE TITLE
Explore how to incorporate authorization into code samples for restricted datasets

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/earthworks#1093]
#1049 is about building in a code sample view.  For restricted datasets, like https://earthworks.stanford.edu/catalog/stanford-cg357zz032, the user must be logged in as a Stanford user in order to view/download the data.  

Questions to answer:

- How does EarthWorks handle authorization for the restricted GeoServer?
- Is it possible to add this authorization to the code sample?

**Comment by hudajkhan** [comment]
Related references:
Proxy controller setup specifically for the restricted GeoServer URL. https://github.com/sul-dlss/earthworks/blob/main/app/controllers/restricted_proxy_controller.rb
EarthWorks shared configs has the specific restricted GeoServer URL to be used. https://github.com/sul-dlss/shared_configs/blob/earthworks-prod/config/settings/production.yml#L9
Looks like EarthWorks puppet also has related configuration. https://github.com/sul-dlss/puppet/blob/production/hieradata/node/earthworks-prod-a.stanford.edu.eyaml#L155


Related issues:
https://github.com/sul-dlss/earthworks/issues/3

**Comment by marlo-longley** [comment]
Find out if this is even possible -- if so, close this exploration ticket, and create an implementation ticket that will depend on the merging of #1100

**Comment by dbranchini** [comment]
Public dataset - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=911-24473&t=KfDIeJaBz5XarlOV-4

Restricted dataset - NOT LOGGED IN - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=911-24351&t=KfDIeJaBz5XarlOV-4

Restricted dataset - LOGGED IN - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=517-18605&t=KfDIeJaBz5XarlOV-4

**Comment by hudajkhan** [comment]
I am going to work on adding this in to the code snippet approach in #1100 as well. I will close this issue and add these examples to #1100

**Comment by marlo-longley** [comment]
See #1125
