### ISSUE TITLE
Solr Synonyms: Review file to see if we want to make any changes to the terms we are searching for 

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/earthworks#1109]
Synonym file: https://github.com/sul-dlss/earthworks/blob/main/config/solr_configs/synonyms.txt

What these lines mean:

- For lines that have only commas, when a query (in the text field) is made for any term on the line, the query expands to include all the terms on the line.   For example, "Harbors,Pier,Quay,Warf" means searching for "Quay" will search for Quay and also for Pier and for Warf (i.e. like an OR search: Harbors OR Pier or Quay or Warf). 
- For lines that have "=>", the query will replace whatever is on the left with a search for whatever terms are on the right.  For example, "Invertebrates => Invertebrates,Lobsters,Mosquitoes,Shellfish" means that a search for Invertebrates will translate to Invertebrates OR Lobsters OR Mosquitoes OR Shellfish. 

The LCSH and ISO sections were retrieved from OGP's repo.  It would be useful to review these to ensure that we want the behavior that will result from the inclusion of these terms. 

In addition, lines that have terms with spaces (e.g. "Public institutions") will break those terms into their individual words at analysis time.  This is not behavior that we want so a separate issue will be created to handle this.

**Comment by kimdurante** [comment]
I've reviewed this file and I think it's good with perhaps one exception: 'chemists' on line 55. 
In my mind, a chemist is a person. Or, I guess it could perhaps be a pharmacy/pharmacist.  However, I don't see that as a synonym for the other terms in the line: Factories,Buildings,Factory,Buildings,industrial,industry,Iron-works,Manufacture,refineries.

I'm fine with keeping it but it seems a little bit odd to me.

**Comment by hudajkhan** [comment]
I can remove 'chemists' from that line, and push the change up with any other changes to the files that need to be made.
