### ISSUE TITLE
Changes to Aardvark mapping

### ISSUE THREAD

**Issue by kimdurante** [sul-dlss/earthworks#1114]
Some changes to the Aardvark metadata mapping

- [x] 1. The following values should be added to the resource class mapping:

   Map: Maps
   dataset: Datasets
   datasets: Datasets

Also, phrases such as "Digital Map" should be detected and included in Map -- anything that contains "maps" or "map".

- [x] 2. Add mapping for creators (dc_creator_sm) with structured name values. An example of a map containing a structured name: [https://purl.stanford.edu/rk962wd2562](https://purl.stanford.edu/rk962wd2562)

I have updated the mapping on line 8 [here](https://docs.google.com/spreadsheets/d/1GV1QK04d870EM5ismR0iHef-9n5bIe5laP0VVjzq0FA/edit?gid=2042286233#gid=2042286233)

- [x] 3. Add mapping for DOIs to dc_identifier_sm. I have updated the mapping on line 22 [here](https://docs.google.com/spreadsheets/d/1GV1QK04d870EM5ismR0iHef-9n5bIe5laP0VVjzq0FA/edit?gid=2042286233#gid=2042286233)
For the issue of displaying the DOI, see https://github.com/sul-dlss/earthworks/issues/1151

- [x] 4. I have changed the mapping for georeferenced (gbl_georeferenced_b) on lines 35-26 [here](https://docs.google.com/spreadsheets/d/1GV1QK04d870EM5ismR0iHef-9n5bIe5laP0VVjzq0FA/edit?gid=2042286233#gid=2042286233)

**Comment by marlo-longley** [comment]
Curious if we can search for the words map/maps in the form genre string

```
"form": [
{
"value": "Early Maps",
"type": "genre"
},
```

**Comment by marlo-longley** [comment]
example of a structured name:
 https://argo.stanford.edu/items/druid:rk962wd2562.json


```
"contributor": [
{
"name": [
{
"structuredValue": [
{
"value": "Ptolemy",
"type": "name"
},
{
"value": "active 2nd century",
"type": "activity dates"
}
]
}
],
"type": "person",
"status": "primary"
},
{
"name": [
{
"structuredValue": [
{
"value": "Waldseemüller, Martin",
"type": "name"
},
{
"value": "1470-1519",
"type": "life dates"
}
]
}
],
```

**Comment by marlo-longley** [comment]
3 -- add DOI to this as well as purl
https://github.com/sul-dlss/searchworks_traject_indexer/blob/4c5d25b90ed8d24f4b6a2e57b75893011737537c/lib/traject/config/geo_aardvark_config.rb#L181

**Comment by marlo-longley** [comment]
4 -- if links to georeferenced map in the Cocina, populate this boolean value

https://github.com/sul-dlss/searchworks_traject_indexer/blob/4c5d25b90ed8d24f4b6a2e57b75893011737537c/lib/traject/config/geo_aardvark_config.rb#L221

should be applied to scanned maps that also have a georeferenced version
keep it unexposed in the UI.

Could make a good storytime if there's time.

**Comment by marlo-longley** [comment]
@kimdurante re: the DOI, should it be displayed under "More Details At" with the Purl (bottom of the page image)? Or somewhere else? I have it indexed into the data, but not sure about the display. I might make this its own design ticket if we aren't sure yet. Thanks!


![Image](https://github.com/user-attachments/assets/30427277-b88b-4f9a-819e-bb2ff9884832)

**Comment by marlo-longley** [comment]
4 -- "To indicate whether or not a scanned map or other imagery has a georeferenced version." (https://opengeometadata.org/ogm-aardvark/#georeferenced)

Current behvior goes to a georef'd map and says yes it is georeferencesd.
What it should be doing is  -- going to a scanned map that has a georeferenced version. 
"True" sholud be on the scanned versions, not the georef'd versions. 

Example: https://purl.stanford.edu/gm036df2527 -- 
The check for "true" may involve checking multiple fields
```
"type": "has other format",
"displayLabel": "Georeferenced Map",
``` 

or

```
{
"structuredValue": [],
"parallelValue": [],
"groupedValue": [],
"value": "https://earthworks.stanford.edu/catalog/stanford-px984sn6906",
"identifier": [],
"displayLabel": "Georeferenced map in EarthWorks",
"note": [],
"appliesTo": []
}
```

we also need to create a new field to hold the Earthworks link.

**Comment by marlo-longley** [comment]
In the case of a georeferenced map we should have data in `dct_source_sm` -- but for example here https://earthworks.stanford.edu/catalog/stanford-kd514jp1398.json the data isn't coming through.
