### ISSUE TITLE
Investigate why metadata model does not work in Earthworks

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1126]
## Backtrace

[earthworks/prod] NoMethodError: undefined method `first' for nil:NilClass

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49895/faults/109836210)

The metadata panel does not work in Earthworks and instead throws an exception (which sends you to the library status page in prod).  This functionality is coming from geoblackight, and we do not think we are overriding it, so it is not clear why it is not working.  We should investigate.

**Comment by marlo-longley** [comment]
Kim says the `/metadata` route is not ever used within our apps.

**Comment by peetucket** [comment]
Quick fix would be to simply redirect this route back to the show page, which would prevent the exception and thus not re-direct to the library show page (possibly ok if we never care about this feature, and I've already tried this locally).  Longer fix would be to investigate why this route seems to work in geoblacklight but not earthworks and then try and make it work in earthworks.

**Comment by peetucket** [comment]
Route: https://github.com/geoblacklight/geoblacklight/blob/56aef6d5a022701c1a9fdb6a44edafaa6c97bbd8/lib/geoblacklight/routes/exportable.rb#L13

Action: https://github.com/geoblacklight/geoblacklight/blob/56aef6d5a022701c1a9fdb6a44edafaa6c97bbd8/lib/geoblacklight/metadata/base.rb

Views: https://github.com/geoblacklight/geoblacklight/tree/56aef6d5a022701c1a9fdb6a44edafaa6c97bbd8/app/views/catalog

_metadata view partial is showing link to modal
metadata view is the actual modal

Note, we seem to be not showing the link to open the modal in Earthworks right now, e.g. https://earthworks.stanford.edu/catalog/stanford-rf515tk4716

**Comment by peetucket** [comment]
It looks like if you don't add the metadata tool partial to the blacklight config (e.g. config.add_show_tools_partial(:metadata) ) ... it doesn't add the action either (from geoblacklight presumably), resulting in an exception if you hit the `/catalog/:ID/metadata` manually.

So if we decide we don't care about the metadata link in the sidebar, we need to figure out how to remove the [route added by geoblacklight ](https://github.com/geoblacklight/geoblacklight/blob/56aef6d5a022701c1a9fdb6a44edafaa6c97bbd8/lib/geoblacklight/routes/exportable.rb#L13) so it can't possibly try and execute the missing action.

The metadata model appears to filter the references in the solr doc for these types of metadata:

https://github.com/geoblacklight/geoblacklight/blob/main/lib/generators/geoblacklight/templates/settings.yml#L93-L98

See https://github.com/geoblacklight/geoblacklight/blob/main/app/views/catalog/_metadata.html.erb#L6-L18 and https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/references.rb#L13-L29

**Comment by peetucket** [comment]
We can create our own `Exportable` routes concern in Earthworks to override what geoblacklight does if we want to remove the metadata route.  This would result in the more expected 404 error if you manually hit a `/catalog/:ID/metadata` URL instead of a server error.

**Comment by peetucket** [comment]
See https://github.com/geoblacklight/geoblacklight/blob/032115d9960c3559124d2b4d03a79f9f245a7012/lib/generators/geoblacklight/templates/catalog_controller.rb#L302

We may already be selectively showing metadata toolbar in geoblacklight based on toolbar existing or not, so perhaps just need to stop overriding in earthworks.

This allows the metadata view to be available and work in earthworks
