### ISSUE TITLE
[earthworks/prod] KeyError: key not found "dct_format_s"

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1127]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49895/faults/109293730)

**Comment by marlo-longley** [comment]
Here are the places we look for populating this field in the aardvard indexer:

```
to_field 'dct_format_s', cocina_descriptive('geographic', 'form'), select_type('data format'), extract_values, translation_map('geo_format')
to_field 'dct_format_s', cocina_descriptive('geographic', 'form'), select_type('media type'), extract_values, translation_map('geo_format')
to_field 'dct_format_s', cocina_descriptive('form'), select_type('form'), extract_values, translation_map('geo_format')
to_field 'dct_format_s', cocina_structural('contains', 'structural', 'contains', 'hasMimeType'), translation_map('geo_format')
```

For this record, druid `fc205rh6942`, of the the 4 possible data sources, the first 3 are empty and contain no data. The last source, `cocina_structural('contains', 'structural', 'contains', 'hasMimeType')` contains the `hasMimeType` values `text/plain`, `application/zip`, and `application/octet-stream`, none of which are handled in the relevant translation map: https://github.com/sul-dlss/searchworks_traject_indexer/blob/e30540ee477d93c53d4a48f111b3974805c875b7/lib/translation_maps/geo_format.yaml#L4

I am not familiar enough with what is expect to know whether we should:
1. handle a nil value for `dct_format_s` in Earthworks
2. accept more mimeTypes or other conditions when indexing this field 
3. create a fallback value in the indexer to populate this field if it is otherwise nil

**Comment by thatbudakguy** [comment]
I think the reason this situation arises is because `dc_format_s` is "conditionally required" as per Aardvark when you have a single `downloadUrl` present in `dct_references_s` – the UI uses the format value to construct the text on the download link, so it will say e.g. "Download original GeoTIFF" if the `dc_format_s` was "GeoTIFF".

The best way to get around this might be to change our implementation of constructing the `downloadUrl` in `dct_references_s` to use [the more structured form detailed here](https://opengeometadata.org/configure-references-links/#multiple-downloads), which is a JSON object that includes labels along with each download. We'd still only have one download link, but we would label it "Zipped object" or something to indicate that it was a stacks download, and that way the UI would not need the `dc_format_s` value to construct the label – it would just use the one we provide. This effectively solves option 1 above, I think.

Option 2 could work, but this format (.grd) doesn't seem to appear in the [list of formats](https://opengeometadata.org/ogm-aardvark/#format-values), and deviating from that is discouraged, so I don't think it's the best option. We might also continue to get things in none of these formats that we want to index.

I'm not sure how we'd do option 3, since something like "Other" isn't allowed per the spec, and I don't think it'd be very useful to users either.

**Comment by thatbudakguy** [comment]
To get the right object structure, I think you would need to insert a transformation step in between `stacks_download_url` and the `as_reference` call to wrap the result like:
```rb
[{ url: stacks_download_url, label: 'Zipped object' }]
```
and then pass this on to `as_reference`. Hopefully the JSON transformation step then does the right thing to escape it.

**Comment by marlo-longley** [comment]
Thanks @thatbudakguy this makes sense. I have something like this going on: 

```
# old version: to_field 'dct_references_s', stacks_object_url, as_reference('http://schema.org/downloadUrl')
to_field 'dct_references_s', stacks_object_url, transform(lambda { |url|
  { 'http://schema.org/downloadUrl' => [{
    url:,
    label: '???'
  }] }
})
``` 

Did you mean that the label should be 'Zipped object' every time? Or would we need to add some kind of translation map?

Then we would need to modify the code around this setting: https://github.com/sul-dlss/earthworks/blob/73d991e883a3f0f6be08429feefee996becdbc48/config/settings.yml#L52 (which is consumed by the upstream GBL DownloadLinksComponent template file)

**Comment by thatbudakguy** [comment]
This looks like exactly what i was thinking! I think it should be "Zipped object" every time (or something like that), since we only ever offer .zip downloads from stacks. Whatever it is, it doesn't depend on the format.

**Comment by thatbudakguy** [comment]
(we could get really fancy and later add more specific things to that `downloadUrl` list, but it's hard for things like Shapefiles that have multiple files, so probably not worth doing right now).
