### ISSUE TITLE
Show an alert if the item is not georeferenced

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1137]
This should only display on items that could conceivably be georeferenced, but are not. One way to check that would be if we're going to render a IIIF viewer, since IIIF content is not georeferenced but might have a version that is.

The actual "is it georeferenced" value comes from [the `gbl_georeferenced_b` field](https://opengeometadata.org/ogm-aardvark/#georeferenced).

![Screenshot 2024-08-08 at 09 54 31](https://github.com/user-attachments/assets/91613b0e-339b-4246-be6c-55636484d5e6)

**Comment by dnoneill** [comment]
@dbranchini Are we doing anything if the item is georeferenced? @kimdurante Is there a way to link to the georeferenced item?

**Comment by dnoneill** [comment]
I do like this method: https://geodiscovery-dev.uwm.edu/catalog/p16022coll230:360
