### ISSUE TITLE
DOI link display

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/earthworks#1151]
~~Blocked by #1114~~

Once we have DOI links in the index, think about how to display them.
The DOI are indexed in an array with the purl in `'dct_identifier_sm'`
Currently the purl displays as part of "More details at" -- do we want add the DOI here?

(see bottom of image)
<img width="919" alt="Screenshot 2024-08-08 at 16 22 18" src="https://github.com/user-attachments/assets/5ad3f4e5-f60c-4d1e-8074-493a1b77ecb0">

**Comment by marlo-longley** [comment]
For now, displaying the whole array under "More details" is fine?

**Comment by dnoneill** [comment]
@peetucket already in the designs.

![Image](https://github.com/user-attachments/assets/31d50432-2f5d-4c9e-bd05-82d56ba35243)

**Comment by peetucket** [comment]
This is the previous work I did that: https://github.com/geoblacklight/geoblacklight/pull/1511/files

It looks in `dct_identifier_sm` field and the `dct_references_s` field for an entry with a key of `http://schema.org/url` and picks one (defaulting to the earthworks URL itself if none exist). 

So we could list both URLs (if found and not the same).  Do we know of other places to look for URLs?  Should we list any others found in the `dct_references_s` field and if so, how we would label them?

**Comment by peetucket** [comment]
https://github.com/geoblacklight/geoblacklight/blob/3e11b2ec01ffd629e89ae9d6e37b0ecb11b26e91/spec/fixtures/solr_documents/esri-tiled_map_layer.json#L62

https://github.com/sul-dlss/searchworks_traject_indexer/pull/1498/files#diff-33aab0e616259a684cfc4e66a6c4bd18664f7b847b63bbd1a04a92614d3b9d28

fk339wc1276

https://github.com/sul-dlss/searchworks_traject_indexer/pull/1498/files

**Comment by marlo-longley** [comment]
Keep `identifier` solr fields in More Details in the metadata section; loop through.
Keep `references` in the sidebar. 
The UI areas should correspond to the location of the Solr data. No fancy parsing.

**Comment by peetucket** [comment]
Remove the Searchworks URL component reference: https://github.com/sul-dlss/earthworks/blob/bl8/app/controllers/catalog_controller.rb#L321-L325

and the component itself.

incorporate searchworks URL into this new component

**Comment by peetucket** [comment]
Closed by #1224
