### ISSUE TITLE
Adjust citation modal view

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1168]
From the record view, we have a link titled, "Cite," which opens a modal with a citation and a button that allows the user to quickly/easily copy the citation. We decided to use PURL links instead of EarthWorks links in the citation. For other institutions, we decided to use the DOI if it exists, and if not, use the schema.org/url link. See attached screenshot from raw data.

1. Removing "Citation info" text.
2. Adjusting the link as described below.
3. Leave the other descriptive text as is.

Here's the citation modal in Figma - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=1439-22090&t=tjCgEkXg4dkqYCNJ-4

NOTE: When the user clicks Copy, the citation is copied to their clipboard and the button changes to active (same as hover - text, icon, and outline color changes from Stanford Digital Blue `#006CB8` to Digital Blue Dark `#00548f`) and displays "Copied." This has been done for code snippets already and buttons are in the [component library](https://github.com/sul-dlss/component-library). 

![Image](https://github.com/user-attachments/assets/17dae9c4-526e-43e6-acf4-450c96b88531)

**Comment by dbranchini** [comment]
Also, remove the words, "Citation info" at the beginning of the citation. I think it's a placeholder before the actual citation.

**Comment by dbranchini** [comment]
For the link 
Look at DCT identifier
If there is at least one value and it is a valid DOI and a link, use that.
If not, then look at DCT references
If there is a references with a key of URL and valid URL, use that.
Otherwise, link to EarthWorks.

**Comment by peetucket** [comment]
Done in geoblacklight.  See https://github.com/geoblacklight/geoblacklight/issues/1500

**Comment by peetucket** [comment]
Fixed by https://github.com/geoblacklight/geoblacklight/issues/1500
