### ISSUE TITLE
Update pagination style

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/earthworks#1170]

**Comment by dnoneill** [comment]
Updated blacklight to have a new theme for pagination. What I heard from the blacklight team is they want this for blacklight9. PR for this is https://github.com/projectblacklight/blacklight/pull/3272. We should be able to update geoblacklight or blacklight to use the new pagination theme by updating the catalog_controller with the lines:

```
config.default_pagination_options = {
      theme: 'blacklight9',
      outer_window: 2
    }
```

**Comment by dnoneill** [comment]
Pagination has been updated to links in earthworks via css. The moving of the next will happen in blacklight9

**Comment by dbranchini** [comment]
Here's some guidance on accessibility:

- https://www.a11ymatters.com/pattern/pagination/
- https://designsystem.digital.gov/components/pagination/#accessibility-guidance (from a design system)
- https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-pagination

Note for the first example, you'll see pagination wrapped in:

`<nav role="navigation" aria-label="Pagination Navigation">`

The `<nav>` element with a role attribute of "navigation" is incorrect. That's a duplication of the same information. It's best practice to use `<nav>` element with a distinct aria-label to distinguish it from other types of navigation on the page.

**Comment by marlo-longley** [comment]
Accessibility issues should be addressed upstream in Blacklight.
