### ISSUE TITLE
Allow the main container to expand further

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1177]
Our current designs for desktop were done with a width of 1608px, but we're currently using bootstrap's default `container` class for the main content, which is often substantially smaller than that on most screens. The result is that the UI looks a little cramped.

To allow more breathing room, especially on the show page, let's try changing the `.container` to a `.container-fluid` and then set a max-width of around 1600px so that it doesn't become too wide on very large screens.

**Comment by marlo-longley** [comment]
Add 60px on side paddding
