### ISSUE TITLE
Design question: "Is part of" area in the right sidebar

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/earthworks#1187]
See the "Is part of" area in the right sidebar 

complex example: https://earthworks.stanford.edu/catalog/p16022coll205:265

Do we need to redesign this?

**Comment by dbranchini** [comment]
@dnoneill showed me this on UAT and it looks good. It should be in the left sidebar in the "context" section - meaning - Item belongs to a collection and Also listed in.

**Comment by dbranchini** [comment]
Reviewed with @dnoneill and in the context section (Item belongs to a collection, also listed in). This is right.
