### ISSUE TITLE
search when I move the map, showing up on item pages

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/earthworks#1192]
see https://earthworks-uat.stanford.edu/catalog/VAC3073-M-00794

![Image](https://github.com/user-attachments/assets/5504877b-98b2-409d-a260-69c0fbc0b148)

**Comment by dnoneill** [comment]
Can't seem to replicate locally. Can't quite figure out what is going on.

**Comment by marlo-longley** [comment]
Will wait until importmaps setup is ready to see if this is still a real issue.

**Comment by dnoneill** [comment]
Believe that this is actually updating the helpers.leaflet_options variable? [https://github.com/geoblacklight/geoblacklight/blob/fcc0a9460662d5ee81ef40943024d9[…]/app/components/geoblacklight/location_leaflet_map_component.rb](https://github.com/geoblacklight/geoblacklight/blob/fcc0a9460662d5ee81ef40943024d900f00f287c/app/components/geoblacklight/location_leaflet_map_component.rb#L28-L32)?

**Comment by dnoneill** [comment]
Testing proved this to be true. Fixed upstream with https://github.com/geoblacklight/geoblacklight/pull/1590

**Comment by thatbudakguy** [comment]
Upstream PR is merged; will be fixed when we update from `main`.
