### ISSUE TITLE
Not working in IE11 on Windows

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#120]
Complains about certificate and mixed loaded content...

![screen shot 2014-12-17 at 3 30 43 pm](https://cloud.githubusercontent.com/assets/1861171/5481151/26b967e0-8602-11e4-9028-febc57df990b.png)

**Comment by eliotjordan** [comment]
I was going to post the IE=Edge workaround for this, but it looks like you fixed this already:
[earthworks.html.erb#L6](https://github.com/sul-dlss/earthworks/blob/master/app/views/layouts/earthworks.html.erb#L6)

I wonder if there is a Rails-y method for adding this back to GeoBlacklight without overriding blacklight.html.erb completely.

**Comment by mejackreed** [comment]
@eliotjordan not that i can think of, but I will submit as a PR to Blacklight. As Blacklight uses Twitter Bootstrap this should be in the default layout.

**Comment by mejackreed** [comment]
@eliotjordan See https://github.com/projectblacklight/blacklight/pull/1058

**Comment by drh-stanford** [comment]
Looks like it's working on IE9 and above: http://www.browserstack.com/screenshots/056f01c98f678e98df5a757fe72eb3af5754f0bd
