### ISSUE TITLE
Download button doesn't fit container

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1201]
https://earthworks-uat.stanford.edu/catalog/f397d257-3587-4b8a-ab40-fdd06f865862

<img width="1013" alt="Screenshot 2024-08-19 at 10 30 59" src="https://github.com/user-attachments/assets/cfb70c38-d2c6-4553-a4b9-dd3a8f2805d0">

**Comment by marlo-longley** [comment]
Closed by #1237
