### ISSUE TITLE
Sidebar headings should be H2

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1219]
H2 for the gray sidebar is 20 pixels, or 1.25 rem (16-pixel base), on the record view. It's shown here - https://www.figma.com/design/FE5WZAvHf2e97GJeOP3mH6/Stanford-Styles?node-id=225-716&t=wotT6ZwLIzZVur4O-4.

**Comment by dnoneill** [comment]
closed in favor of https://github.com/sul-dlss/earthworks/issues/1213
