### ISSUE TITLE
Left align metadata labels on record view

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1220]
Metadata labels should be left-aligned so they can be scanned more quickly/easily. The record view should be adjusted per the following - https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=911-24473&t=wbfBPbfvy5YnCPZw-4.

**Comment by dnoneill** [comment]
closed with https://github.com/sul-dlss/earthworks/pull/1235
