### ISSUE TITLE
UI - Active facets on search results

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1254]
Note the design of the active facets:

![Image](https://github.com/user-attachments/assets/0908422e-be26-4135-b52e-3c7a2ef2ad14)

https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=1455-30297&t=tgedhB7ZESbVxGHG-4

(Ignore the facet panel (left side bar) on these designs. It's still under discussion with the POs.)

**Comment by dnoneill** [comment]
Closing in favor of #1209

Question on the PR right now is should be doing this for all applications, not just earthworks.
