### ISSUE TITLE
Active facet colors on facet sidebar 

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1262]
We're in the final stretch, so this might not be possible at this late stage. I've mentioned that there isn't a consensus among the POs for the facet panel, so we don't yet have a single solution to use across applications. I have two proposals; one might be easier to implement than the other. I prefer Solution 2, but I'm not attached to it. Solution 1 is more similar to the default.

Solution 1 

<img src="https://github.com/user-attachments/assets/1d3f9506-8478-4690-a4da-8f72720aaef4" width="250">

Solution 2

<img src="https://github.com/user-attachments/assets/6fe038a0-668e-4843-a8ec-cf6a2d3aa9b3" width="250">

**Comment by peetucket** [comment]
Is solution 1 the same background color as the header banner?

**Comment by hudajkhan** [comment]
I tried it out locally and the darker color is visible.
