### ISSUE TITLE
Add padding to the bottom of the facet panel on search results

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1274]
This is only an issue if someone open a bunch of facets and the height exceeds the height of the search results. 

![Image](https://github.com/user-attachments/assets/4130b86d-a1ee-4ada-95fe-bdd1c156faee)

**Comment by edsu** [comment]
I don't think I'm seeing this on UAT?

Firefox:
![Image](https://github.com/user-attachments/assets/59b7d830-fd30-495e-9a82-d4e3e6eb0d3c)

Chrome:
![Image](https://github.com/user-attachments/assets/4fc4ee8f-1e7e-473c-bb81-8a0df087f59e)

**Comment by dnoneill** [comment]
@dbranchini I think this has been fixed. I am seeing the same thing as Ed. Can you confirm?

**Comment by dbranchini** [comment]
Yep, looks fixed! Thanks!
