### ISSUE TITLE
Change the Bootstrap columns on search results page

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1276]
I'm mainly speaking about how this renders on a 16-inch Mac laptop (or larger), so I'm happy to hop on a call to cover different breakpoints together. We are currently rendering search results as follows:

- Facets sidebar -- 3 columns 
- Search results + map panel -- 9 columns
-- Search results -- 6 columns 
-- Map panel -- 6 columns

Proposed solution:
- Facets sidebar -- 2 columns 
- Search results + map panel -- 10 columns
-- Search results -- 7 columns 
-- Map panel -- 5 columns
 
This is what it looks like with the proposed solution:

![Image](https://github.com/user-attachments/assets/ca5edfe4-18c6-49ad-8fdb-b4e0a62e81a7)

**Comment by dbranchini** [comment]
The search results + map panel looks good, but the facets sidebar should be 2 columns and the search results + map panel should be 10 columns at an XXL breakpoint. It might not work at a XL or L breakpoint. Let's huddle on it when you have it open.

**Comment by marlo-longley** [comment]
@dnoneill Is this closeable?

**Comment by dnoneill** [comment]
Yup
