### ISSUE TITLE
Remove extra border around facets on mobile view

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1277]
Each facet has a border, so we do not need to wrap all of them with another border. It's only happening on mobile view. Also, I think we need to center "Limit your search" and the "Show/Hide facets" button vertically. And lastly, if possible, the button should be a primary outline button instead of the default gray. 

<img src="https://github.com/user-attachments/assets/8e14f67f-136f-492a-bbb9-684e9ab95897" width="250">

<img src="https://github.com/user-attachments/assets/c1479cdf-fe2c-4e6b-a7ed-834147aa91c0" width="250">

**Comment by hudajkhan** [comment]
The border line appears to come in from Blacklight: https://github.com/projectblacklight/blacklight/blob/main/app/assets/stylesheets/blacklight/_facets.scss#L52

**Comment by hudajkhan** [comment]
For the border color for the button, would you mind providing a similar example or the color you like? I assume you want btn-primary-outline (or similar) but just want to confirm.  

Also, I am applying the spacing changes only to the mobile version.  Is the correct? Or would you like to change the border color for all window sizes, not just mobile?

**Comment by hudajkhan** [comment]
The PR above addresses the section border and spacing, but not the button itself.  It might be good to do a different PR overriding the button as a whole/using the component as opposed to just CSS changes.

**Comment by hudajkhan** [comment]
Also, the button doesn't exist in the desktop version, so that answers one of my questions above.

**Comment by dbranchini** [comment]
It should use the primary blue outline button seen here - https://sul-dlss.github.io/component-library/button/. Pick a size that's closest to the button that's there now.

**Comment by hudajkhan** [comment]
Thanks.  For reference, the code for the "show/hide facets" button is here: https://github.com/projectblacklight/blacklight/blob/main/app/components/blacklight/response/facet_group_component.html.erb

**Comment by jcoyne** [comment]
This may have been an inadvertent change in Blacklight https://github.com/projectblacklight/blacklight/commit/32373178d88f529855adbb73df3630865a8e53ba. Can we fix it there?

**Comment by jcoyne** [comment]
Actually, it's just easer to set `  --bl-facets-smallish-border: none;`

**Comment by hudajkhan** [comment]
Closed by #1309
