### ISSUE TITLE
Search input on search results and record detail view

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1279]
The search input looks larger in both width and height than designed. It's about 520 pixels on XXL, XL, L, M, S viewport sizes and full width on XS [as designed](https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=335-13898&t=Mk1sK8D8gfmkr0Bx-4). It's also 47 pixels in height. Here's the specs in Figma:

Search icon - 24 pixels (width and height)
Text - 16 pixels 
Search button - 31 pixels (height) 

Search button is the largest in height, then there's 8 pixels padding top/bottom so that ends up being 47 pixels. I know it's done differently in code, so I don't expect it to match perfectly, just wanted to provide the full specs.

**Comment by marlo-longley** [comment]
#1317 fixed most of this except for the magnifying class icon sizing.
