### ISSUE TITLE
header line not even

### ISSUE THREAD

**Issue by dnoneill** [sul-dlss/earthworks#1283]
![Image](https://github.com/user-attachments/assets/6f6691aa-3211-4da6-92cc-4238fbc8bfa3)

**Comment by jcoyne** [comment]
This is a Blacklight bug. https://github.com/projectblacklight/blacklight/blob/69373f202753f04ec6aca179fdf8fa01248a9edf/app/assets/stylesheets/blacklight/_controls.scss#L10-L11

**Comment by dnoneill** [comment]
@jcoyne Thanks that made it easier to track down the fix.
