### ISSUE TITLE
Homepage main container does not expand to fill page

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1290]
There's extra whitespace on the bottom. Think we might need some `flex` on this guy.

![Image](https://github.com/user-attachments/assets/46eae67f-eaf0-42d5-bae3-06da089cc95f)

**Comment by dnoneill** [comment]
I am not seeing this. What browser and version are you using?

**Comment by thatbudakguy** [comment]
Firefox 130.0b9

**Comment by thatbudakguy** [comment]
And Chrome 130.0.6686.0

**Comment by marlo-longley** [comment]
@thatbudakguy I also cannot reproduce this.

**Comment by jcoyne** [comment]
@thatbudakguy I've done this in other sites: https://github.com/sul-dlss/purl/blob/main/app/assets/stylesheets/application.css#L15-L18.
