### ISSUE TITLE
Bookmark button doesn't use pointer cursor

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#1292]
Might be a blacklight thing? When I tested, adding `cursor: pointer;` to the `<label class="toggle-bookmark">` solved it (but not any of its parent elements).

**Comment by dnoneill** [comment]
Yeah looks to be a blacklight thing: https://demo.projectblacklight.org/?search_field=all_fields&q=

**Comment by dnoneill** [comment]
PR open in BL https://github.com/projectblacklight/blacklight/pull/3305

**Comment by dnoneill** [comment]
Closed upstream. Earthworks needs a Gemfile update and it will go into effect.
