### ISSUE TITLE
No colons on dt (metadata labels)

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1298]
Currently, the metadata labels have colons after them. Please remove the colons. 

https://www.figma.com/design/nkgg905s5FyXoyPZjVMco0/EarthWorks?node-id=911-24518&t=Mxo8GLwgXQqO5i98-4.

**Comment by dnoneill** [comment]
Upstream issue in blacklight https://github.com/projectblacklight/blacklight/issues/3303
