### ISSUE TITLE
KMZ should be replaced with CSV

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1300]
Datasets should have the following export options:

Shapefile
CSV (instead of KMZ)
GeoJSON

For example, this dataset - https://earthworks-uat.stanford.edu/catalog/stanford-wk478kp5122

**Comment by dnoneill** [comment]
I I am not sure I understand this. We provide a download for a CSV if they exist.

**Comment by hudajkhan** [comment]
@dbranchini am I correct in interpreting this to mean that we don't want to show KMZ at all, and instead incorporate a CSV option for all datasets (where KMZ would have been applicable in the past)?

**Comment by hudajkhan** [comment]
As @dnoneill pointed out, our download links appear to be generated based on what is listed in Solr, so this may need some more clarification.

**Comment by dbranchini** [comment]
@hudajkhan No KMZ at all, that's correct, and it will be replaced with the CSV option.

**Comment by kimdurante** [comment]
In GeoServer, under Layer Preview, in the All Formats drop-down, CSV downloads are available in the list of WFS options.

Example: [https://earthworks-geoserver-pub-prod-a.stanford.edu/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?7&filter=false](https://earthworks-geoserver-pub-prod-a.stanford.edu/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?7&filter=false)

**Comment by hudajkhan** [comment]
I set up this PR in GeoBlacklight to allow a CSV download option to be added and configured through settings: https://github.com/geoblacklight/geoblacklight/pull/1583

**Comment by hudajkhan** [comment]
Closed by #1350
