### ISSUE TITLE
Copy for the home page

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1316]
Geospatial Datasets
Data that includes location information (coordinates) and is natively usable in GIS software and services such as ArcGIS, QGIS, WFS, and WMS. Geospatial data types include vector data, such as Shapefile, GeoJSON, and GeoPackage, and raster data, such as GeoTIFF, grid files, and georeferenced maps.

Maps
Images of paper maps that have been scanned and/or georeferenced. These digital cartographic resources cover all parts of the world and include topographical maps, historical maps, nautical charts, thematic maps, and atlases.

**Comment by marlo-longley** [comment]
Also check the count logic given new indexing data

**Comment by dbranchini** [comment]
Geospatial Datasets (note the change to the heading too)
Data that includes location information (coordinates) and is natively usable in GIS software and services such as ArcGIS, QGIS, WFS, and WMS. Geospatial data types include vector data, such as Shapefile, GeoJSON, and GeoPackage, and raster data, such as GeoTIFF, grid files, and georeferenced maps. There are over **[number] datasets** in EarthWorks.

Button reads "Browse all datasets"

Maps
Images of paper maps that have been scanned and/or georeferenced. These digital cartographic resources cover all parts of the world and include topographical maps, historical maps, nautical charts, thematic maps, and atlases. There are over **[number] maps** in EarthWorks.

Button reads "Browse all maps"

Number of datasets = Resource class = dataset (button should go to this too)
Number of maps = Resource class = map (button should go to this too)

**Comment by kimdurante** [comment]
Under Geospatial Datasets, can we change 'GeoTIFF' to 'GeoTIFFs'?
