### ISSUE TITLE
Map facet buttons blue not red

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/earthworks#1340]
See "maps"

<img width="941" alt="Screenshot 2024-08-30 at 16 16 16" src="https://github.com/user-attachments/assets/3dab8cb6-282b-4e91-a02d-274362f4a662">

**Comment by dnoneill** [comment]
I would hold off on doing this ticket. Unless I am misunderstanding, I believe it is already being addressed.

**Comment by peetucket** [comment]
It's still red in this PR: https://github.com/sul-dlss/earthworks/pull/1242  

Is there other work that should address it?

**Comment by peetucket** [comment]
In conflict with the newer ticket #1355
