### ISSUE TITLE
Active facets should appears as they are in Figma

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1355]
I believe this was done once already?

---
**Currently on UAT:**

<img src="https://github.com/user-attachments/assets/e7181923-aa50-4d4b-8c2c-d3f1d61ec95e" width="500">

---
**As designed:**

<img src="https://github.com/user-attachments/assets/9105fbf1-5e56-4d65-9592-2590eef4c213" width="600">

**Comment by dnoneill** [comment]
This will be closed with updating the component library
