### ISSUE TITLE
Background colors seem to be missing on the footer and alerts

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1365]
This might be a component library issue. I've attached screenshots of the issues I'm seeing.

---
**Record view - alert that it's not georeferenced**
![Image](https://github.com/user-attachments/assets/0558da24-7d3b-4c93-8550-b8f6f700b66c)

---
**Successfully logged out alert**
![Image](https://github.com/user-attachments/assets/219ad1cf-c99a-42e4-8402-c34a9fa3b48e)

---
**Footer**
![Image](https://github.com/user-attachments/assets/8a330ba3-0d2d-4228-9369-d7b757bb93da)

**Comment by dnoneill** [comment]
Footer closed with https://github.com/sul-dlss/earthworks/pull/1368

Alerts closed with https://github.com/sul-dlss/component-library/pull/47. 

Need to cut a new release of the component library and import to earthworks.
