### ISSUE TITLE
subject normalization to LCSH for federated metadata

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#138]
Princeton's FGDC-derived and the OGP network metadata sometimes use non-normalized subject headings. Investigate whether we can cross-walk these subjects with LCSH.

**Comment by drh-stanford** [comment]
This should probably move to OpenGeoMetadata.

**Comment by thatbudakguy** [comment]
Aardvark [explicitly allows non-controlled vocab for Subject](https://opengeometadata.org/ogm-aardvark/#subject), so this seems lower priority (and would be something to discuss for OGM anyway).
