### ISSUE TITLE
Minimum target size error on links on record view

### ISSUE THREAD

**Issue by dbranchini** [sul-dlss/earthworks#1381]
This might be a false positive, but we're getting this on several links on this page, including:

Back to search results
Under export:
- Shapefile 
- KMZ
- GeoJSON
Under also listed in:
- SearchWorks 

It needs to be at least 24 x 24 pixels, which it seems that it would be as 16px and a line-height of 24px, but the computed in Chrome inspector shows auto/auto for the height/width. Also, when I inspect other links, they also seem to have the same specs, but they are not throwing this error.

**Comment by thatbudakguy** [comment]
Pretty sure this is a false positive. None of these can be shorter than 24px and they're all longer than that. The inspector shows the interactive area for the `<a>` is correct.

![Image](https://github.com/user-attachments/assets/8c2953df-0d12-4ccb-8690-9e44a1b9908a)

**Comment by dbranchini** [comment]
@thatbudakguy it isn't the length, it's the height that shows 23 for me when I inspect them in Chrome. I'll just leave this for now and we can reopen if it comes up in the official SiteImprove review.
