### ISSUE TITLE
Strange tile behavior for a Georeferenced Map on item page.

### ISSUE THREAD

**Issue by mapninja** [sul-dlss/earthworks#1423]
https://earthworks.stanford.edu/catalog/stanford-jz864sc3723

In the default map view for the item, the map tiles are not visible until you zoom in one or two steps. If you Zoom Out to the full world extent, a strange set of tiles is superimposed on the map below the equator. 

Default View, no map:
![image](https://github.com/user-attachments/assets/dedb4656-50ad-4d8d-acfe-1753a79cc2c5)

Zoomed, with map:
![image](https://github.com/user-attachments/assets/a9bdfe38-179f-4a91-9a73-f6cc9e1c4f59)

Zoomed out to Globe with weird tiles:
![image](https://github.com/user-attachments/assets/c3e54921-8091-434a-996c-5e4091f4251a)

Tile Caching issues?

**Comment by kimdurante** [comment]
This is resolved
