### ISSUE TITLE
Items still appearing in EarthWorks search results after being withdrawn

### ISSUE THREAD

**Issue by kimdurante** [sul-dlss/earthworks#1428]
I used the manage release tool to withdraw some scanned maps from EarthWorks. However, they are still appearing in the search results. See this example here:
[https://earthworks.stanford.edu/?search_field=all_fields&q=Kita%C4%AD](https://earthworks.stanford.edu/?search_field=all_fields&q=Kita%C4%AD)

When you click on a result link, nothing happens. The objects themselves appear to be withdrawn - they are not accessible from their individual EarthWorks URLs.

**Comment by thatbudakguy** [comment]
I think this might just be a case of the index being slow to update. Let's give it a day or so to catch up.

**Comment by kimdurante** [comment]
Thanks for the info @thatbudakguy !

Looks like this is resolved.
