### ISSUE TITLE
Send email to hydra / blacklight dev community asking for feedback

### ISSUE THREAD

**Issue by bess** [sul-dlss/earthworks#143]

**Comment by jcoyne** [comment]
Just stumbled upon this. :+1: Earthworks is super cool. The only suggestion is that some results (e.g.: https://earthworks.stanford.edu/catalog/minnesota-census2000tigercombinedtracts1990-2000 ) have "Original" in the dropdown, but it's not clickable. What's that about?

**Comment by mejackreed** [comment]
@jcoyne Thanks for your feedback on this. "Original" refers to the original file download. Layers/documents with web services allow for derivative "Generated" downloads too. See https://earthworks.stanford.edu/catalog/stanford-mh274gx7614

![screen shot 2015-01-13 at 6 56 00 am](https://cloud.githubusercontent.com/assets/1656824/5722485/474c17c4-9af1-11e4-98f7-77926d149656.png)

Some of these layers have both "Original" and "Generated" downloads

We have definitely gone around and around on what to call these different types of downloads. Your feedback here is valuable.

https://github.com/geoblacklight/geoblacklight/issues/167
https://github.com/geoblacklight/geoblacklight/issues/146 (with mocks of design)

**Comment by jcoyne** [comment]
For the uninitiated (me), who are not familiar, it looks like there's an "Original" option that is disabled. This leaves me wondering "Why can't I download the original?"

**Comment by mejackreed** [comment]
Thanks @jcoyne. I wonder if adding a divider might make it clearer?

![screen shot 2015-01-13 at 3 10 16 pm](https://cloud.githubusercontent.com/assets/1656824/5731242/50568954-9b36-11e4-8221-aa73497842bd.png)

**Comment by jcoyne** [comment]
@mejackreed I'm not sure that helps a lot.  Perhaps don't show "original/generated" if there is only one option in the list?
