### ISSUE TITLE
layers with date ranges in metadata not working

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#173]
From Kim

I'm noticing a possible display issue with the metadata expressing temporal subjects. This data layer contains data from a range of years = 2001-2003. 
However the display shows 2001, 2003.
Additionally, this item's PURL page uses a ">" symbol instead of a hyphen to express this range.

**Comment by mejackreed** [comment]
Solr 5 is supporting date range fields... Maybe let's wait for that? https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+4+to+Solr+5

**Comment by drh-stanford** [comment]
Yes, the `DateRangeField` seems like the right implementation. In the meantime, we need to fix the GeoBlacklight metadata transformation to support at a minimum for `dct_temporal`

* YYYY
* YYYY-YYYY

and then `solr_year_i` will take the first (earliest) year (this breaks the semantics but there's not much we can do in Solr4).

**Comment by thatbudakguy** [comment]
fixed: https://earthworks.stanford.edu/catalog/stanford-zv296hf8888
