### ISSUE TITLE
Ingest UVA data from OpenGeoMetadata

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#179]
https://github.com/OpenGeoMetadata/edu.virginia

**Comment by drh-stanford** [comment]
- [ ] Load UVa data into Solr dev
- [ ] Add UVa icon to EarthWorks dev
- [ ] Validate in dev
- [ ] Push to stage/prod

**Comment by mejackreed** [comment]
@drh-stanford UVA icons are already apart of GeoBlacklight

**Comment by drh-stanford** [comment]
Duplicate for #337
