### ISSUE TITLE
Verify that More details at link is actual URL

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#183]
We need to verify that the "More details" link is an actual (http/https/ftp) URL. The UVa data are just using UUIDs there which link to nowhere and have no protocol. 

See #179 
https://kurma-earthworks-dev.stanford.edu/catalog/uva-Albemarle:AgForest2004

**Comment by mejackreed** [comment]
Do we have a GeoBlacklight-Schema validator? This could be useful to prevent some of these data issues? Could be part of https://github.com/OpenGeoMetadata/GeoCombine?

**Comment by mejackreed** [comment]
https://github.com/OpenGeoMetadata/GeoCombine/issues/1

**Comment by drh-stanford** [comment]
We have a schema validation tool here https://github.com/geoblacklight/geoblacklight-schema/pull/33. But the `dct_references_s` is a complex data type (a hash table of URI=>URL in JSON syntax), so we'd need some custom validation code for it.

**Comment by mejackreed** [comment]
Ok so maybe the GeoCombine method `validate` would validate the using the xslt and then also validate the JSON in `dct_references`?

**Comment by mejackreed** [comment]
This now seems resolved
