### ISSUE TITLE
Upgrade to Solr BBox field type

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#193]
- [ ] Change `solr_bbox` to `BBox` type in GeoBlacklight schema (see https://github.com/geoblacklight/geoblacklight-schema/pull/37, now see https://github.com/geoblacklight/geoblacklight-schema/pull/39)
- [ ] Change Earthworks/GeoBlacklight to use `solr_geom`
- [ ] Change GeoBlacklight tests and config (https://github.com/geoblacklight/geoblacklight/pull/284)
- [ ] Change generators to not output `solr_bbox` in schema?
- [ ] Upgrade sul-solr instances schema (sul-solr is now 4.10)
- [ ] other...

**Comment by mejackreed** [comment]
See https://github.com/geoblacklight/geoblacklight-schema/pull/37, https://github.com/geoblacklight/geoblacklight/pull/292
