### ISSUE TITLE
add service for cleaning cache periodically

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#205]
through some "smart" means -- LRU by downloads...

**Comment by drh-stanford** [comment]
see https://jirasul.stanford.edu/jira/browse/SAR-2636

**Comment by mejackreed** [comment]
See https://github.com/geoblacklight/geoblacklight/issues/306

**Comment by thatbudakguy** [comment]
definitely still an issue; seems [we've just increased the cache size gradually](https://stanfordlib.slack.com/archives/C060ZTZRV/p1625587361034300) and never pruned it. might be solved/addressed as part of https://github.com/geoblacklight/geoblacklight/issues/294.

**Comment by jmartin-sul** [comment]
if we go with the LRU cache cleaning approach (versus e.g. switching to an approach where we don't cache the generated file on the server): we've used the `find` command with the `amin` (last accessed N minutes ago) flag for cleaning the cache from a cron job in other codebases ([example here](https://github.com/sul-dlss/preservation_catalog/blob/49eac1f7747d957ba6ac494ed7b526f853a33f28/lib/tasks/prescat.rake#L100-L103)).

**Comment by peetucket** [comment]
After looking through slack thread, it appears the task is to clear old files in ` /var/cache/earthworks` on earthworks servers.  it appears the server names in the slack thread (`kurma-earthworks1-prod` and `kurma-earthworks1-prod`) are older and are now `earthworks-prod-a.stanford.edu` and `earthworks-prod-b.stanford.edu`

**Comment by thatbudakguy** [comment]
that is correct; there is a more recent map of the infrastructure in the devopsdocs for earthworks
