### ISSUE TITLE
Typo in footer

### ISSUE THREAD

**Issue by bess** [sul-dlss/earthworks#217]
In the footer on earthworks.stanford.edu there is a typo in the url for "My Account":

hhttp://library.stanford.edu/myawrap.html

There's an extra "h" at the front of the url & this causes a broken link.

**Comment by cbeer** [comment]
@mejackreed Did you steal the footer from searchworks (which had this same typo), or is there some other common source where we should fix it?

**Comment by mejackreed** [comment]
Yes was stolen from SearchWorks and fixed there by @jkeck https://github.com/sul-dlss/SearchWorks/commit/524d4cbbfafb5aeea64276cdec98d56e3520ce86 ... SW deploy hasn't gone out yet though.
