### ISSUE TITLE
title and abstract appear to be missing for salmon data [GeoServer]

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#229]
vv853br8653

This potentially affects people using the wms or wfs services directly.
![screen shot 2015-04-03 at 8 03 16 am](https://cloud.githubusercontent.com/assets/1656824/6983906/e907992e-d9d7-11e4-8bfc-f78698a383b8.png)

**Comment by drh-stanford** [comment]
fixed
