### ISSUE TITLE
Linking to an old facet (not available causes an error)

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#230]
https://earthworks.stanford.edu?bbox=-14.370117+33.504759+10.019531+46.860191&f%5Bdc_rights_s%5D%5B%5D=Restricted

**Comment by cbeer** [comment]
Is it a blacklight error or something in your app?

**Comment by mejackreed** [comment]
Not sure... diagnosing a few errors right now. Might be a GeoBlacklight error.

**Comment by mejackreed** [comment]
Temporarily fixed by #232
