### ISSUE TITLE
error with data for 

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#234]
https://earthworks.stanford.edu/catalog/stanford-v802xm5496

Looks like there may be a space in the index id

**Comment by drh-stanford** [comment]
https://earthworks.stanford.edu/catalog/stanford-v802xm5496%20.json

@kdurante, there's an extra trailing space in this ISO metadata:

```xml
  <fileIdentifier>
    <gco:CharacterString>edu.stanford.purl:sv802xm5496 </gco:CharacterString>
  </fileIdentifier>
```

**Comment by drh-stanford** [comment]
fixed in prod
