### ISSUE TITLE
Google indexing search results

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#239]
Google is indexing our search results, not just the sitemap URLs. Maybe we can modify `robots.txt` somehow to prevent crawling queries? Not sure how to force crawlers to only do sitemap URLs...

For example, google: earthworks salmon stanford.

![screen shot 2015-04-09 at 10 49 07 am](https://cloud.githubusercontent.com/assets/1861171/7073117/1479a96c-dea6-11e4-995a-a0e9b8954c21.png)

our `robots.txt` is:

```
Sitemap: https://earthworks.stanford.edu/sitemaps/sitemap.xml.gz
User-agent: *
Disallow:
```

**Comment by drh-stanford** [comment]
Maybe add a meta robots noindex to the search results pages?

  http://www.robotstxt.org/meta.html

**Comment by mejackreed** [comment]
We can do this I believe using the Google Webmaster tools... ill look into it. Do we want something like top level facets indexed?

**Comment by mejackreed** [comment]
I propose this config:

```txt
Disallow: /catalog?*
Disallow: /catalog/?*
Disallow: /catalog?q=*&
Disallow: /catalog/?q=*&
Allow: /catalog?q=*
Allow: /catalog/?q=*
Disallow: /?*
Allow: /?q=*
```

It will allow specific queries to be indexed, but leaves out facets

**Comment by drh-stanford** [comment]
and it allows slugs to be indexed, e.g., /catalog/stanford-aa111bb2222. it looks ok to me.

**Comment by mejackreed** [comment]
I made some light mods to our Google Webmaster tools... is it ok if we put a pin in this for a few days to see how that works?

**Comment by drh-stanford** [comment]
sure

**Comment by drh-stanford** [comment]
Google is still indexing facets:

```
66.249.79.28 - - [21/Apr/2015:13:08:01 -0700] "GET /?f%5Baccess%5D%5B%5D=available&f%5Bdc_format_s%5D%5B%5D=Shapefile&f%5Bdc_publisher_s%5D%5B%5D=Afghanistan+Information+Management+Service&f%5Blayer_geom_type_s%5D%5B%5D=Line&sort=score+desc%2C+dc_title_sort+asc HTTP/1.1" 200 56878 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

**Comment by mejackreed** [comment]
Updated robots.txt

**Comment by drh-stanford** [comment]
Might want to consider a "noindex" meta tag in our search results pages:

```
<meta name="robots" content="noindex" />
```
