### ISSUE TITLE
More details at, incorrect for xm762yy5032

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#242]
https://earthworks.stanford.edu/catalog/stanford-xm762yy5032

**Comment by drh-stanford** [comment]
@kimdurante the `dataSetURI` in the ISO isn't using a purl...

```xml
  <dataSetURI>
    <gco:CharacterString>xm762yy5032</gco:CharacterString>
  </dataSetURI>
```

**Comment by kimdurante** [comment]
oh no! I'll change that...

**Comment by kimdurante** [comment]
this has been fixed and the new file is at:
METADATA/EURATLAS/xm762yy5032/temp

**Comment by drh-stanford** [comment]
fixed in prod
