### ISSUE TITLE
earthworks needs better nagios monitoring

### ISSUE THREAD

**Issue by bess** [sul-dlss/earthworks#251]
Currently, nagios monitoring for EarthWorks says everything is green even though spatial search is broken: https://newcaprica.stanford.edu/nagios/cgi-bin/status.cgi?hostgroup=earthworks&style=detail

EarthWorks needs monitoring around spatial search, keyword search, data downloads, at least. Also, we should be monitoring each node of earthworks, plus the load balanced name.

**Comment by mejackreed** [comment]
For restricted layers:
https://earthworks.stanford.edu/catalog/stanford-fp756wn9369

Public:
https://earthworks.stanford.edu/catalog/stanford-cz128vq0535

Spatial search and file download

**Comment by mejackreed** [comment]
Setup with @tallenaz
