### ISSUE TITLE
typo in uuid

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#254]
https://earthworks.stanford.edu/catalog/stanford-sf815vr1246

has http://purl.sanford.edu/sf815vr1246

**Comment by drh-stanford** [comment]
@kimdurante

**Comment by kimdurante** [comment]
our file versions might be out of sync? the XML file I have for this item,
located here:
METADATA/MBARI_1/sf815vr1246/temp

does not contain this typo. It was updated in January. hope that helps...

**Comment by drh-stanford** [comment]
it was accessioned on Jan 5 2015 at noon. maybe I didn't have the update by then.

**Comment by drh-stanford** [comment]
fixed.
