### ISSUE TITLE
Layer not in GeoServer stanford-gy826dj4762

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#256]
@drh-stanford 

https://earthworks.stanford.edu/catalog/stanford-gy826dj4762

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/gis-robot-suite/issues/32

**Comment by drh-stanford** [comment]
also causes a funky state for the login/download tool. i'm logged in but says to login to download...

![screen shot 2015-04-17 at 8 58 31 am](https://cloud.githubusercontent.com/assets/1861171/7205726/2c5a0b68-e4e0-11e4-8fd8-73272f96c6d9.PNG)

**Comment by mejackreed** [comment]
Yep I added this separately as #255

**Comment by drh-stanford** [comment]
I've deleted this object from the -prod index. if you want to test, i kept it in -stage:

  https://kurma-earthworks-stage.stanford.edu/catalog/stanford-gy826dj4762

**Comment by drh-stanford** [comment]
this is pending re-accessioning and tracked in sul-dlss/gis-robot-suite#32
