### ISSUE TITLE
missing icon for Attribution Share Alike 3.0 Unported

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#274]
See example here:

  https://earthworks.stanford.edu/catalog/stanford-bf137pp5814

which uses the `by_sa` tag.

**Comment by drh-stanford** [comment]
I discovered the source of the incorrect "by_sa" code. It was in the public domain APO back in 9-17-2013 and wasn't removed until 1-29-2015. So unfortunately any item that was registered during this time under the public domain APO likely has the wrong rightsMetadata. I will remediate them via a scriptie.

**Comment by mejackreed** [comment]
:+1: @drh-stanford !!

**Comment by drh-stanford** [comment]
this is fixed for the 158 objects in EarthWorks

**Comment by mejackreed** [comment]
:laughing:
