### ISSUE TITLE
Error with layer placename metadata? zz281cq9133

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#277]
https://earthworks.stanford.edu/catalog/stanford-zz281cq9133

Tagging @kimdurante on this

**Comment by kimdurante** [comment]
Can you elaborate on the error?

**Comment by kimdurante** [comment]
n'mind. i think i see it. the abstract needs to be updated.

**Comment by mejackreed** [comment]
Sorry, listed "Cananda" as a placename

**Comment by mejackreed** [comment]
Resolved.
