### ISSUE TITLE
Arabic characters not rendering properly in metadata view

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#281]
The arabic characters appear to be stored in Solr correctly, but they are not being rendered correctly in the metadata view.

Example:

https://earthworks.stanford.edu/catalog/stanford-xh656zc2650

![screen shot 2015-08-11 at 2 05 02 pm](https://cloud.githubusercontent.com/assets/1861171/9210594/01dc2e5e-4032-11e5-87db-bf5072514d77.png)

and in Solr:

![screen shot 2015-08-11 at 2 05 41 pm](https://cloud.githubusercontent.com/assets/1861171/9210600/12e3bfd2-4032-11e5-88d3-c2c474ba2e4a.png)

**Comment by mejackreed** [comment]
What browser are you using here? Can you check the console to see if the Source Sans Pro font was downloaded? Working for me in Chrome, Firefox and Safari

**Comment by drh-stanford** [comment]
The screenshots where I see the problem are from Chrome 44.0.2403.130 (64-bit). It does work in Safari for me. The network log shows that it downloads https://fonts.googleapis.com/css?family=Source+Sans+Pro with a 200 status code.

**Comment by mejackreed** [comment]
Strange... any privacy extensions you are using?

**Comment by drh-stanford** [comment]
this is working for me now
