### ISSUE TITLE
reindex UMinn

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#283]
they have rebuilt their index and now have fewer layers...

**Comment by mejackreed** [comment]
I'm wondering if we could outline the challenges here to reindexing / removing content.

**Comment by drh-stanford** [comment]
priority. it's behind a bunch of other accessioning work. https://jirasul.stanford.edu/jira/secure/RapidBoard.jspa?rapidView=402&view=planning&quickFilter=561

**Comment by mejackreed** [comment]
Gotcha... Anything that GeoCombine can do to make this easier?

**Comment by drh-stanford** [comment]
The code in https://github.com/geoblacklight/geoblacklight-schema/tree/master/tools/ogp already does the ugly business of cleaning up and transforming the OGP records into GeoBlacklight. I don’t know whether we want to migrate that code (ogp -> geoblacklight) into GeoCombine — it’s pretty nasty. We’re probably better off waiting for OGP to support CSW for harvesting OGP sites.

**Comment by mejackreed** [comment]
Ok sounds good!

**Comment by drh-stanford** [comment]
See -dev index

**Comment by drh-stanford** [comment]
Duplicate of #337
