### ISSUE TITLE
qn309jc5979 doesn't seem to be in SDI

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#289]

**Comment by drh-stanford** [comment]
This layer is in the Restricted GeoServer, not the Public. we need to re-run `gisDeliveryWF` and `gisDiscoveryWF`

cc @kimdurante

**Comment by kimdurante** [comment]
ok. this is a public domain layer but part of ESRI Data and Maps.

**Comment by kimdurante** [comment]
this should work now
