### ISSUE TITLE
Odd behavior with display of GIS object at maximum zoom level

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/earthworks#297]
https://earthworks.stanford.edu/catalog/stanford-tg926kp6619

<img width="582" alt="zoomed-out" src="https://cloud.githubusercontent.com/assets/96776/13854174/6cbb9024-ec27-11e5-8d3a-36b03ca1920f.png">
<img width="585" alt="zoomed-in" src="https://cloud.githubusercontent.com/assets/96776/13854173/6cb683c2-ec27-11e5-868b-32ec8faa2ece.png">

**Comment by mejackreed** [comment]
Thanks @jkeck is there a tix from jira we can reference?

**Comment by jkeck** [comment]
SW-1617
