### ISSUE TITLE
Add link to view in SearchWorks

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#310]
Potentially could be troublesome as records can be unreleased

**Comment by drh-stanford** [comment]
related to https://github.com/sul-dlss/earthworks/issues/403

**Comment by thatbudakguy** [comment]
We could consider doing this by making a request to purl-fetcher at render time to check (live) whether the thing actually is released to SearchWorks.

**Comment by peetucket** [comment]
Example items released to both environments available via Argo: https://argo-stage.stanford.edu/catalog?f%5Breleased_to_earthworks%5D%5B%5D=ever&f%5Breleased_to_searchworks%5D%5B%5D=ever

**Comment by peetucket** [comment]
https://purl.stanford.edu/rb811tg2000.xml
https://opengeometadata.org/reference-uris/

Add schema.org Related Link key/value pair to `dct_refererences_s` field in earthworks traject in searchworks_traject_indexer

as_reference macro

geo_aardvark_config.rb

**Comment by thatbudakguy** [comment]
steps to accomplish this:

- [ ] add a method to [`PurlRecord`](https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/purl_record.rb) that can access release tag metadata to determine what platforms the record is released to
- [ ] add a new setting for the searchworks base URL, similar to [`settings.purl_url`](https://github.com/sul-dlss/searchworks_traject_indexer/blob/41309f7af6513aaeade73d9ad1d02cc08a515265/lib/traject/config/geo_aardvark_config.rb#L48)
- [ ] add a new macro to [`Traject::Macros::Cocina`](https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/macros/cocina.rb) (similar to `purl_url`) that generates a searchworks view URL using the base URL _if_ the record is released to searchworks
- [ ] call the macro in the aardvark config to add the searchworks URL to `dct_references_s` with a key of [https://schema.org/relatedLink](https://schema.org/relatedLink) (see [how it works for purl URLs](https://github.com/sul-dlss/searchworks_traject_indexer/blob/41309f7af6513aaeade73d9ad1d02cc08a515265/lib/traject/config/geo_aardvark_config.rb#L268))

**Comment by peetucket** [comment]
`echo "hj948rn6493" | bundle exec traject --debug-mode -c lib/traject/config/geo_aardvark_config.rb -s reader_class_name=Traject::DruidReader --stdin`
