### ISSUE TITLE
Missing icons for Multi* geometries

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#316]
We have an icon for MultiPoint, but not MultiLineString or MultiPolygon

![screen shot 2016-08-01 at 1 36 24 pm](https://cloud.githubusercontent.com/assets/1861171/17308089/ffdcf2b8-57ec-11e6-8ac2-afec2b07bd62.png)

**Comment by mejackreed** [comment]
See: https://github.com/geoblacklight/geoblacklight-icons/issues/20
