### ISSUE TITLE
Search box on homepage not functional in Safari

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#317]
In Safari, you cannot select or type into the search box. The JavaScript console has lots of errors like this:

![screen shot 2016-08-02 at 1 10 11 pm](https://cloud.githubusercontent.com/assets/1861171/17343465/a8b27a5a-58b2-11e6-8190-4ba0c8f064da.png)

Works fine in Chrome.

See https://kurma-earthworks-dev.stanford.edu/

**Comment by drh-stanford** [comment]
Upgraded to  font-awesome-rails (4.6.3.1) with no luck. Still getting errors in bootstrap-sass, like this

```
/* line 112, /Users/drh/.rvm/gems/ruby-2.2.2/gems/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_carousel.scss */
.carousel-control.right {
    left: auto;
    right: 0;
    background-image: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
    background-image: -o-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
    background-image: linear-gradient(to right, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
    background-repeat: repeat-x;
    filter: progid: DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1);
}```

```

**Comment by mejackreed** [comment]
This seems to also be happening in:
 - GeoBlacklight https://geo.nyu.edu/
 - Blacklight 7 @ demo.projectblacklight.org

I think this has something to do with the Blacklight JavaScript, perhaps the autocomplete.

**Comment by eliotjordan** [comment]
This looks OK in Blacklight 7.01. This might be fixed. We should check to be sure on GeoBlacklight 2.0.

**Comment by mejackreed** [comment]
Resolved upstream
