### ISSUE TITLE
Add EarthWorks, SSDI, and GeoMonitor to DevOpsDocs

### ISSUE THREAD

**Issue by bess** [sul-dlss/earthworks#318]
Please document EarthWorks, SSDI and GeoMonitor in DevOpsDocs (https://github.com/sul-dlss/DevOpsDocs). Ensure that someone other than Darren or Jack could respond to a pager duty alert. Create a SAR to add these to Pager Duty.

**Comment by drh-stanford** [comment]
See https://jirasul.stanford.edu/jira/browse/SAR-3209

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/DevOpsDocs/pull/28

**Comment by mejackreed** [comment]
Resolved with merge of https://github.com/sul-dlss/DevOpsDocs/pull/28
