### ISSUE TITLE
Make OnClick buffer larger for line and point features?

### ISSUE THREAD

**Issue by mapninja** [sul-dlss/earthworks#323]
Currently, it's difficult at any zoom level to click on a point or line feature to activate the table preview. Is it possible to create a buffer for onClick in Leaflet?

**Comment by thatbudakguy** [comment]
testing with https://earthworks.stanford.edu/catalog/stanford-vx572wx7854, this doesn't seem so difficult anymore? closing, but we can reevaluate if needed
