### ISSUE TITLE
turn on OpenSearch for distributed searching

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#330]
See https://github.com/sul-dlss/earthworks/blob/master/app/views/layouts/application.html.erb

It should call the following code to enable the OpenSearch API:

https://github.com/projectblacklight/blacklight/blob/master/app/views/layouts/blacklight/base.html.erb#L20

**Comment by mejackreed** [comment]
Can we call this complete now? See:
https://earthworks.stanford.edu/catalog/opensearch.xml
