### ISSUE TITLE
geoserver pub in production taking too long to boot

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#332]
@julianmorley reports that it's taking > 40 mins to reboot.

see https://github.com/geoserver/geoserver/wiki/GSIP%20155

**Comment by drh-stanford** [comment]
this is fixed in GeoServer 2.11 -- see https://github.com/sul-dlss/operations-tasks/issues/1572

**Comment by drh-stanford** [comment]
we may want to consider using JDBCConfig which stores all of the catalog data in an RDBMS rather than .xml files -- see http://docs.geoserver.org/stable/en/user/community/jdbcconfig/index.html

**Comment by mejackreed** [comment]
Seems to be resolved with some of our GeoServer updates.
