### ISSUE TITLE
Build a new index

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#337]
- Existing SDR
  - [x] SUL
- Existing OGP
  - [x] Harvard (has broken webservices links)
  - [x] Tufts
  - [x] MIT
- Drop OGP
  - [x] UCLA
  - [x] UCB
  - [x] Columbia
- Add OGM
   - [x] NYU
   - [x] Columbia
   - [x] Princeton
   - [x] UCB
- Add OGM to evaluate
  - [x] Big 10
  - [x] UVA
- Add from GeoBlacklight instances
  - [ ] Lewis & Clark
  - [ ] BPL
  - [ ] Cornell
- [x] Yes: Decide on whether to upgrade all records to v1.0 schema via GeoCombine enrichment
- [x] Implement pre-1.0 metadata upgrading
- Deployment
  - [x] Development to Stage
  - [x] Stage to Production

cc: @kimdurante

**Comment by mejackreed** [comment]
I'm not sure if we care that much? If it is fairly easy.. then sure lets keep the same, but if it is a big thing perhaps we can drop it.

cc @mapninja

**Comment by drh-stanford** [comment]
I can migrate some of it over, but it's basically a bunch of messy heuristics -- https://github.com/geoblacklight/geoblacklight-schema/blob/ogp/tools/ogp/2_transform.rb#L324-L348

**Comment by mejackreed** [comment]
Sounds good. I'm good with migrating to something more maintainable if that makes sense moving forward.

**Comment by drh-stanford** [comment]
What do we want to do with `geoblacklight.json` files in OGM that are pre-1.0? Should we try to upgrade them automagically? Or just drop them?

**Comment by mejackreed** [comment]
Hmm.. Do we have a list  of institutions where this is happening? I think it would be great if we could issue a PR with the updates.

**Comment by drh-stanford** [comment]
I don't have a list of institutions, but Columbia has pre-1.0 metadata -- https://github.com/OpenGeoMetadata/edu.columbia/blob/master/ESRI_Arcatlas_snow_ln/geoblacklight.json

The upgrade is straight-forward and I can add it to GeoCombine but I need to find (or rewrite) the code that upgrades the schema from pre-1.0 to 1.0.

**Comment by drh-stanford** [comment]
I have the upgrade (pre-1.0 to 1.0) code in a PR now -- https://github.com/OpenGeoMetadata/GeoCombine/pull/79

**Comment by drh-stanford** [comment]
we are currently running GeoMonitor on all the harvested layers in the -dev Solr index that has the re-harveseted OGP and OGM metadata.

**Comment by drh-stanford** [comment]
Just a note on how I'm ingesting the layers:

for OGP:

```
cd ~/earthworks/current/scripts/indexing/ogp
# generate the geoblacklight.json file following README instructions
OGM_PATH=`pwd` SOLR_URL='...' bundle exec rake geocombine:index
```

for OGM

```
cd ~/earthworks/current
mkdir /var/tmp/opengeometadata
bundle exec rake earthworks:opengeometadata:pipeline
```

**Comment by mejackreed** [comment]
@drh-stanford I think we may have missed Cornell here: https://github.com/OpenGeoMetadata/edu.cornell Should we look into adding?

**Comment by mejackreed** [comment]
Both Cornell and L&C are in OGM now I think.

**Comment by drh-stanford** [comment]
Yes, I have Cornell and L&C as ingest via their GeoBlacklight instances not OGM. I'll add them to the blessed OGM instances here -- https://github.com/sul-dlss/earthworks/blob/master/lib/tasks/earthworks.rake#L125-L133

**Comment by mejackreed** [comment]
I noticed that the Big 10 geoportal hosts metadata that is not in their OGM repo. For example, Maryland has 1677 layers available here: https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Maryland&q=&search_field=all_fields

A lot of these seem like things we would like to have.

**Comment by drh-stanford** [comment]
Implementing https://github.com/sul-dlss/earthworks/issues/398 would allow us to harvest directly from their GeoBlacklight instance. We would need to develop a strategy for resolving records between their OGM and GeoBlacklight instance (for example, the instance copy may be preferred if they are different).

I'm in favor of closing this issue and moving onto https://github.com/sul-dlss/earthworks/issues/398 to get the last 3 institutions we have above (L&C, Cornell, and BPL).
