### ISSUE TITLE
"More details" link for non-Stanford layers

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#341]
- [x] Decommission opengeometadata-rails (is used for HTML preview of metadata)
- [x] Modify "More details" link to use built-in GeoBlacklight metadata modal

**Comment by drh-stanford** [comment]
related to #354

**Comment by drh-stanford** [comment]
The "More details" link for OGP metadata points to nowhere in the revised index because we don't have the OGM pointer. For OGM metadata, we're relying on the institution to provide a reference.

**Comment by drh-stanford** [comment]
Request made -- see https://github.com/sul-dlss/operations-tasks/issues/1586
