### ISSUE TITLE
Setup automated sitemap generation

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#362]
Perhaps using whenever? But I'm not seeing this update automatically.

**Comment by drh-stanford** [comment]
There's capistrano tasks for refreshing `cap xxx sitemap:refresh` -- see https://github.com/kjvarga/sitemap_generator/blob/master/lib/capistrano/tasks/sitemap_generator.cap

**Comment by drh-stanford** [comment]
There's also rake tasks too `rake sitemap:refresh` -- see https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/tasks.rb
