### ISSUE TITLE
Fix hosts in earthworks-prod shared_configs

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#376]
The -prod branch has kurma-earthworks-prod1 hardcoded when it should allow -prod2, etc. See https://github.com/sul-dlss/shared_configs/blob/earthworks-prod/config/settings/production.yml#L4-L6

There's also several outstanding PRs for shared_configs:

https://github.com/sul-dlss/shared_configs/pull/440
https://github.com/sul-dlss/shared_configs/pull/441
https://github.com/sul-dlss/shared_configs/pull/442
https://github.com/sul-dlss/shared_configs/pull/443
https://github.com/sul-dlss/shared_configs/pull/444

**Comment by drh-stanford** [comment]
I don't understand the issue here anymore :(

**Comment by mejackreed** [comment]
:) close it now?
