### ISSUE TITLE
audit for which Stanford layers should be in EarthWorks

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#387]
We have some number mismatches between SDR and EarthWorks -- roughly on the order of a few dozen layers. We need to audit to discover what's missing or wrong.

The list of layers that made it through to EarthWorks is here: https://raw.githubusercontent.com/OpenGeoMetadata/edu.stanford.purl/2dce51f8fcf02ba524396452afe0461f9594146b/layers.json

The list of layers in Argo have mismatches between the `gis*WF` workflows:

<img width="303" alt="screen shot 2018-01-18 at 1 51 53 pm" src="https://user-images.githubusercontent.com/1861171/35124309-7ac6c63a-fc5a-11e7-899e-9d6b5899611e.png">

This list of layers actually in EarthWorks is here: https://kurma-earthworks-stage.stanford.edu/catalog?f%5Bdct_provenance_s%5D%5B%5D=Stanford
cc @kimdurante

**Comment by kimdurante** [comment]
These 2 txt files contain the druids missing gisDelivery and gisDiscovery workflows.

Once you are done with your work I can update these. And I'll look at the discrepancies between the EW records. It's a small number and we had this issue once a while ago with duplicates. So I'd like to see why that's happening.

4 of the druids listed will not have the gisDiscoveryWF enacted. I'll contact you about perhaps setting up a system by which we can identify those (maybe a tag in Argo)

[gisDiscoveryWF.txt](https://github.com/sul-dlss/earthworks/files/1647683/gisDiscoveryWF.txt)
[gisDeliveryWF.txt](https://github.com/sul-dlss/earthworks/files/1647684/gisDeliveryWF.txt)

**Comment by drh-stanford** [comment]
ths gisDiscoveryWF have run in production for those druids (minus the 4 which I accidentally ran gisDiscoveryWF for but deleted from the Solr index)

**Comment by drh-stanford** [comment]
@kimdurante is going to run the gisDeliveryWF for the druids above tomorrow.

**Comment by drh-stanford** [comment]
> I'll contact you about perhaps setting up a system by which we can identify those (maybe a tag in Argo)

@kimdurante i think we can use the embargo functionality in Argo for this. The GIS robots won't know about the embargo because we don't support that, but at least it'll give us information about which layers should not go out via `gisDiscoveryWF`

**Comment by drh-stanford** [comment]
so the next step is for @kimdurante to re-upload all of the "`temp`" stage data for all the gisDeliveryWF layers, and then fire off the `gisAssemblyWF`, `gisDeliveryWF`, etc.

**Comment by kimdurante** [comment]
@drh the list of druids to be deleted deleted from the EW index
[deleteDruids.txt](https://github.com/sul-dlss/earthworks/files/1666105/deleteDruids.txt)

**Comment by drh-stanford** [comment]
ok these have been deleted. is there anything else to do on this ticket?

**Comment by drh-stanford** [comment]
@kimdurante durante there's some unavailable Stanford layers that have gone through gisDeliveryWF but are not available in GeoServer. For example, https://earthworks.stanford.edu/catalog/stanford-wy669nz2521

**Comment by kimdurante** [comment]
ok. i'll take a look

**Comment by thatbudakguy** [comment]
this is being addressed by current work on the robots; namely https://github.com/sul-dlss/argo/issues/3893 and related.
