### ISSUE TITLE
Convert our current index maps into GeoJSON adopting OpenIndexMap spec

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#388]
Our current index maps are shapefiles accessioned in SDR. We need to create GeoJSON files with the appropriate attribute tables corresponding to the OpenIndexMaps spec https://github.com/OpenIndexMaps/openindexmaps.github.io/blob/master/index.md

**Comment by drh-stanford** [comment]
@kimdurante, we should be able to just copy in a `data.json` file into the druid folder in the stage directory (along with `data.zip`) and it _should_ work ok -- I need to test it out though.

**Comment by drh-stanford** [comment]
@kimdurante will accession the index map with the GeoJSON file -- after Stace finishes that data

**Comment by drh-stanford** [comment]
so we need to change the GIS robots (mods2geoblacklight.xslt?) to insert a dct_reference for openindexmaps (see https://github.com/geoblacklight/geoblacklight/pull/588/files#diff-d9b96e0620799d0b287b30b03fc629b0R24) whenever there is a Subject of `Index maps`

**Comment by drh-stanford** [comment]
@kimdurante in stage, you need to create a folder called `content` next to the `temp` folder. drop a `index_map.json` in there and the accessioning pipeline will push it to stacks.

**Comment by drh-stanford** [comment]
i solved this another way -- if you put an `index_map.json` file into the `content` folder for the layer in accessioning, it'll add the index map dct_reference. See https://github.com/sul-dlss/gis-robot-suite/pull/130

**Comment by drh-stanford** [comment]
@stacemaples likes the idea of using the same convention as the shapefiles, with the geojson named the same as the data. so we'll need to modify `gis-robot-suite` to be more flexible about the file naming.

**Comment by drh-stanford** [comment]
we have an index map layer with the openindexmaps stuff accessioned here https://earthworks.stanford.edu/catalog/stanford-ts545zc6250
