### ISSUE TITLE
Follow up with institutions about unavailable data

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#389]
With our new GeoMonitor updates, we should contact institutions about unavailable data

**Comment by drh-stanford** [comment]
See https://github.com/OpenGeoMetadata/edu.nyu/issues/17

**Comment by andrewbattista** [comment]
@mejackreed Just following through here: I addressed the 12 null island bounding box layers that Darren identified. I added valid geoms to them, but for whatever reason, the layers are not previewing in GeoServer. The "preservation record" is working though, and the metadata records have been updated in opengeometadata

**Comment by mejackreed** [comment]
Resolved or stale
