### ISSUE TITLE
index quality assessment

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#394]
- [ ] Looks like alot/all of the Princeton scanned maps are giving an “Unavailable for download” message, but I am able to preview and download the ones I spot checked.
- [ ] Looks like none of the Princeton map previews are getting a basemap
- [ ] Bad metadata here -- https://kurma-earthworks-stage.stanford.edu/catalog/stanford-cz837nz3249
- [ ] Bad dates from Michigan -- https://kurma-earthworks-stage.stanford.edu/?utf8=%E2%9C%93&q=&search_field=dummy_range&range%5Bsolr_year_i%5D%5Bbegin%5D=2019&range%5Bsolr_year_i%5D%5Bend%5D=10000&range%5Bsolr_year_i%5D%5Bbegin%5D=2018&range%5Bsolr_year_i%5D%5Bend%5D=10000&commit=Limit
- [ ] Looks like lots of issues with UVa data. Vector looks good for the most part, but it looks like there are issues with most raster layers. some are messaging unavailable, some aren’t previewing…
- [ ] when I facet to ‘unavailable’ on NYU data, the search list map breaks
- [ ]  WHen I click on the “more details” on this NYU Unavailable layer, I’m forwarded to Stanford SSO, then forwarded to the page https://kurma-earthworks-stage.stanford.edu/catalog/nyu_2451_36796
- [ ] Maryland has the same issue as Princeton with scanned maps messaging “unavailable’ but previewing and downloading, albeit without basemap

**Comment by mejackreed** [comment]
>  Looks like none of the Princeton map previews are getting a basemap

That is because they are ungeoreferenced IIIF layers. There is no basemap.
See: https://kurma-earthworks-stage.stanford.edu/catalog/princeton-qf85nd24c

**Comment by mejackreed** [comment]
>  Looks like lots of issues with UVa data. Vector looks good for the most part, but it looks like there are issues with most raster layers. some are messaging unavailable, some aren’t previewing…

Yep I'm seeing just that their GeoServer sends back empty png's. This is happening directly from their GeoServer. Nothing we can do here except contact them.

**Comment by mejackreed** [comment]
>  when I facet to ‘unavailable’ on NYU data, the search list map breaks

I think that the map is just zoomed in really far here. Can you try zooming out? @mapninja

**Comment by mejackreed** [comment]
>  Maryland has the same issue as Princeton with scanned maps messaging “unavailable’ but previewing and downloading, albeit without basemap

THese are IIIF layers w/ no basemap. (not georeferenced)

**Comment by mejackreed** [comment]
> WHen I click on the “more details” on this NYU Unavailable layer, I’m forwarded to Stanford SSO, then forwarded to the page

That sounds really strange. I just tested and could not replicate.

**Comment by mapninja** [comment]
> when I facet to ‘unavailable’ on NYU data, the search list map breaks
> I think that the map is just zoomed in really far here. Can you try zooming out? @mapninja

Yup, Null Island. Assuming the metadata is there, shouldn't we still get a proper extent/scale and extent boxes onHover?

**Comment by mejackreed** [comment]
I don't think so. This seems like an issue/feature with Leaflet. Checkout: http://jsbin.com/juwugitono/edit?html,output

**Comment by thatbudakguy** [comment]
no longer relevant; we can conduct another index assessment if we want
