### ISSUE TITLE
Add "cron job" or something for running GeoMonitor periodically

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#401]
We want to run the `update` and `check_stanford`, `check_public` tasks at some regular interval. We can use the `whenever` gem to do this I think. We just need to define the frequency (i.e., semi-daily, daily, weekly, etc.)

**Comment by mejackreed** [comment]
Proposal:
 - `update` usually takes at least 20minutes to run. Perhaps that at least daily
 - `check_stanford` - every 6 hours?
 - `check_public` - every other day?

**Comment by drh-stanford** [comment]
That's a good starting point -- weekly may be too infrequent to bump layers out of Unavailable.
