### ISSUE TITLE
add synonyms to Solr index for better searching results

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#41]
OGP has synonym files that handled LCSH and more.

https://github.com/OpenGeoportal/ogpSolrConfig/tree/master/ogpSolrConfig/SolrConfig

**Comment by thatbudakguy** [comment]
work to be done here:

- copy the synonym .txt files from the link at top into the `config/solr_config` directory of this repo
- update the `schema.xml` and/or `solrconfig.xml` in this repo to make the analyzers take account of the synonym files
- test it out locally to see if synonym-based searching works (e.g. "CO" or "colo" should give results for "Colorado")
- if it works, make the same changes to the solr config in `sul-solr-configs`
- do a reindex, if needed? (might not be needed if we only apply synonyms at query time)
- consider making the same changes in geoblacklight

**Comment by hudajkhan** [comment]
The solr configuration and schema files in the repository are already out of sync with our latest changes to Aardvark.  As part of this PR, I will also update the files to reflect what we have in sul-solr-configs before adding the changes.
