### ISSUE TITLE
Reindex Columbia metadata

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#414]
Based on discussion here: https://github.com/OpenGeoMetadata/edu.columbia/issues/2

New web service urls have been published

**Comment by drh-stanford** [comment]
I've reindexed these in -dev, -stage, and -prod cores. It'll take a week or so for GeoMonitor to put them in. I didn't see any easy way to remove all the GeoMonitor statuses for a given institution.

**Comment by drh-stanford** [comment]
done
