### ISSUE TITLE
[earthworks/prod] ActionView::Template::Error: The asset "geospatial_data.png" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#417]
## Backtrace

    line 15 of [PROJECT_ROOT]/app/views/catalog/_home_text.html.erb: block in _app_views_catalog__home_text_html_erb___2145687228722410948_38151560
    line 14 of [PROJECT_ROOT]/app/views/catalog/_home_text.html.erb: _app_views_catalog__home_text_html_erb___2145687228722410948_38151560

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49895/faults/36381964)

**Comment by drh-stanford** [comment]
Note that this is happening on the **worker** box...

**Comment by mejackreed** [comment]
So is a bot hitting the worker box? Maybe the solution here is to block traffic to it not on the Stanford network or vpn range? I'm thinking we intentionally don't setup this app the web app profile.

**Comment by drh-stanford** [comment]
It's not a bot -- in fact, the request (a HEAD request) is coming from 127.0.0.1. I'm wondering if having passenger installed is the problem?  do we need passenger for the worker boxes?

https://github.com/sul-dlss/puppet/blob/production/hieradata/node/kurma-earthworks-worker-prod-a.stanford.edu.eyaml#L41-L44

**Comment by cbeer** [comment]
I've disabled passenger preflight on the worker boxes.
