### ISSUE TITLE
Handle display of unavailability warning message for unknown institutions

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#418]
## Backtrace

    line 23 of [PROJECT_ROOT]/app/models/solr_document.rb: contact_email
    line 7 of [PROJECT_ROOT]/app/views/catalog/_show_message.html.erb: _app_views_catalog__show_message_html_erb__4558754593061420921_47353080
    line 15 of [PROJECT_ROOT]/app/views/catalog/_show_default.html.erb: _app_views_catalog__show_default_html_erb___4042069617143190044_46856560

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49895/faults/36376035)

**Comment by drh-stanford** [comment]
we have Purdue in the provenance -- perhaps we need a generic warning message?

```
"layer_slug_s": "1d8b2277-f32e-491b-9ccd-93aa247a3336",
"dct_provenance_s": "Purdue",
```

**Comment by thatbudakguy** [comment]
can be resolved by adding logic to: https://github.com/sul-dlss/earthworks/blob/effa3519c0d035c9fb17b23e43b3a4daa1682c62/app/views/catalog/_show_message.html.erb#L7

to handle the case where we have a layer displaying that doesn't have a contact email listed in:
https://github.com/sul-dlss/earthworks/blob/effa3519c0d035c9fb17b23e43b3a4daa1682c62/config/settings.yml#L119

**Comment by thatbudakguy** [comment]
Note that Aardvark has [a special solr field](https://opengeometadata.org/ogm-aardvark/#display-note) that will automatically result in an HTML alert being displayed on the page. We could use that to add warning message at index time instead of dynamically in the app.

**Comment by peetucket** [comment]
Are there any example druids that have this problem currently?  May be helpful for testing.

**Comment by kimdurante** [comment]
There are some records I've seen from other institutions that display this message when there is a downloadable object. An example is this one from Illinois:
https://earthworks.stanford.edu/catalog/a07f9c70-994e-0134-2096-0050569601ca-8

If you click through to their site, there are download options available. However, this might be something on their end that we cannot correct.

An unavailability message also displays on some collection records, which might be a little confusing:
https://earthworks.stanford.edu/catalog/12d-02
