### ISSUE TITLE
install robots.txt on geoservers

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#424]
We're getting bot traffic on our GeoServers. For example:

```
66.249.79.135 - - [15/Feb/2018:10:42:07 -0800] "GET /geoserver/gwc/rest/seed/druid:by617mn8672 HTTP/1.1" 401 1073 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

**Comment by thatbudakguy** [comment]
Needs investigation to see if this is still relevant/an issue. I think robots.txt can be managed via puppet.

**Comment by edsu** [comment]
We are definitely still seeing bot traffic. In the last 7 hours we've seen:

Googlebot: 980
Bingbot: 244
GPTBot: 4

I'm proceeding with the understanding that we can block all crawlers from Geoserver, since people will be getting that content to index by viewing Earthworks, SearchWorks and PURL.

**Comment by edsu** [comment]
New robots.txt files are in place on:

- earthworks-geoserver-pub-prod-a.stanford.edu
- earthworks-geoserver-pub-prod-b.stanford.edu
- earthworks-geoserver-stage-a.stanford.edu
- earthworks-geoserver-stage-b.stanford.edu
- earthworks-geoserver-stan-prod-a.stanford.edu
- earthworks-geoserver-stan-prod-b.stanford.edu

The robots.txt contains:

```
User-Agent: *
Disallow: /
```
