### ISSUE TITLE
Georeferencing is off for vn977hm3834

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#496]
See https://earthworks.stanford.edu/catalog/stanford-vn977hm3834

@kimdurante @mapninja

**Comment by kimdurante** [comment]
yes, the project team is aware of this and is going to redo this and send us another file.

thanks!

**Comment by mejackreed** [comment]
Nice!

**Comment by kimdurante** [comment]
This is a really cool collection of maps! You might see a few more like this but they are working on updating the georeferencing...

**Comment by thatbudakguy** [comment]
Appears to be fixed now!
