### ISSUE TITLE
Data previews not showing on restricted layers when logged in. 

### ISSUE THREAD

**Issue by mapninja** [sul-dlss/earthworks#547]
Previews and attribute query are not currently working for restricted layers, when logged into the SU network. Derivative downloads from the Geoserver do seem to be working, though. 

Shib issues?

https://earthworks.stanford.edu/catalog/stanford-wr560qy3766

**Comment by mejackreed** [comment]
More information in #452 and #470

**Comment by mejackreed** [comment]
I'm thinking the following is happening:

1. A Stanford user logs in for the first time, no problems viewing the data
2. EarthWorks keeps the user session active
3. User comes back to the application, the user still has an active session in the application, but the shib auth needs to be reauthed.
4. The web map requests map tiles that are redirected through shib `https://earthworks.stanford.edu/restricted/geoserver/wms?service=WMS&request=GetMap&layers=druid%3Awr560qy3766&styles=&format=image%2Fpng&transparent=true&version=1.1.1&tiled=true&CRS=EPSG%3A900913&width=256&height=256&srs=EPSG%3A3857&bbox=-10331840.239250705,2817774.6107047372,-10018754.171394622,3130860.67856082` but never get displayed by the webmap.
