### ISSUE TITLE
Regularly update metadata records from OpenGeoMetadata

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#639]
Similar to #591, but maybe also support other GeoBlacklight's?

https://geodata.wisc.edu has some great data in it

**Comment by thatbudakguy** [comment]
We could probably start doing this by writing a new background job that uses GeoCombine to clone/pull/index opengeometadata records on a regular basis.

**Comment by edsu** [comment]
I was just reminded by @andrewjbtw that the metadata in question being pulled in here is for non-Stanford items. So there is no need to update SDR or worry about it stomping on any updates that are pulled in.
