### ISSUE TITLE
Hide icons in "Tools" menu

### ISSUE THREAD

**Issue by jvine** [sul-dlss/earthworks#647]
For each link in the Tools menu, there's an icon followed by text. Currently the icon name is read as part of the link text.

Add `aria-hidden="true"` to the `<svg>` for each of these.

<img width="303" alt="Screen Shot 2020-06-12 at 2 19 10 PM" src="https://user-images.githubusercontent.com/6945691/84547146-c8700a80-acb7-11ea-8c16-71e89ad0cc17.png">

**Comment by ggeisler** [comment]
This is not related to the issue but is small enough that I'll just ask here: should we add the external link icon to the "Open in Carto" link? It feels a bit odd to have only one link in the list without an icon.

**Comment by jvine** [comment]
While we're on it, web services isn't an external link but a modal popup. So.
