### ISSUE TITLE
Should we always link to additional metadata?

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/earthworks#651]
It seems that for SDR items that use the sul-embed viewer (I think that's the determining factor?), we don't show a link to additional metadata in the sidebar Tools menu.

For example, here's an item that doesn't use the sul-embed viewer :

<img width="973" alt="Screen Shot 2020-06-12 at 4 29 02 PM" src="https://user-images.githubusercontent.com/101482/84553880-4d641f80-acca-11ea-9a76-f0f0d6e10723.png">

https://earthworks.stanford.edu/catalog/stanford-zb162wk6653

---

And here's one that does:

<img width="973" alt="Screen Shot 2020-06-12 at 4 29 31 PM" src="https://user-images.githubusercontent.com/101482/84553903-610f8600-acca-11ea-8095-31a954262cf3.png">

https://earthworks.stanford.edu/catalog/stanford-gk885tn1705

---

I understand that the embed viewer provides access to additional metadata, but I'm wondering if it wouldn't be better to remove the inconsistency and always show the Tools metadata link? The viewer metadata isn't super obvious to users who haven't previously explored the viewer features, and seeing the availability of the Tools metadata link on some pages but not others could be confusing.

**Comment by mejackreed** [comment]
Potentially related, we could (and probably should) add the metadata links for the Stanford non-geo content to the indexing.

**Comment by thatbudakguy** [comment]
This is being resolved by unzipping our `data.zip`s and linking to their constituent files. Now a data problem, not a software problem.
