### ISSUE TITLE
Adjust the visible lines in the show page Description expand/collapse

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/earthworks#652]
This might be a GeoBlacklight thing because I think I saw it on other institutions' implementations, but I don't see it on others (geo.nyu.edu) so I'm not sure where it should be fixed.

I consistently see partial text at the bottom of the item show page Description field when additional field text is collapsed:

<img width="726" alt="Screen Shot 2020-06-12 at 4 42 11 PM" src="https://user-images.githubusercontent.com/101482/84554331-30c8e700-accc-11ea-9f46-25c3117facfc.png">

https://earthworks.stanford.edu/catalog/stanford-zb162wk6653

---

**Comment by cbeer** [comment]
I believe this was fixed when we swapped out readmore for our own expand/collapse widget.
