### ISSUE TITLE
Strip spaces from SVG icon text used in item show page title

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/earthworks#653]
When you hover over one of the icons used in the title of the item show page the resulting "popup" (whatever it's called) has extra space above, below, and to the left of the actual text:

<img width="568" alt="Screen Shot 2020-06-12 at 5 00 08 PM" src="https://user-images.githubusercontent.com/101482/84554806-8ef6c980-acce-11ea-9de0-ec03f7271a9b.png">

which looks kind of weird.

It appears that in the SVG code there is a space before and after the text:

<img width="233" alt="Screen Shot 2020-06-12 at 5 04 08 PM" src="https://user-images.githubusercontent.com/101482/84554921-147a7980-accf-11ea-967d-d77b9de5b053.png">

Stripping those spaces seems to fix the problem:

<img width="568" alt="Screen Shot 2020-06-12 at 4 59 29 PM" src="https://user-images.githubusercontent.com/101482/84554931-1e9c7800-accf-11ea-8ac4-d5aa067049f9.png">

--- 

A related question: are these icons important enough (they're certainly very prominent) that we should present a better explanation of them, rather than relying on the SVG title text? 

For example, a BS4 tooltip would enable the text to be more visible (larger, on a more distinct container that includes a pointer to the icon it is associated with). If we went that way we might also consider adding a label, so that the tooltip reads "Format: Raster" or "Institution: Stanford". I'm inclined to think these are prominent enough, and the range of format icons wide enough, that they deserve a more deliberate presentation like the tooltip.

**Comment by mejackreed** [comment]
Resolved with upstream work
