### ISSUE TITLE
Download / Export ambiguous link text

### ISSUE THREAD

**Issue by jvine** [sul-dlss/earthworks#659]
On the show page, the download and export links have ambiguous link text.

<img width="275" alt="Screen Shot 2020-06-15 at 5 44 53 PM" src="https://user-images.githubusercontent.com/6945691/84719344-f8c1de00-af2f-11ea-8465-3d69f61f22bf.png">

Export in particular: visually, you have to look to the left of the button to see the meaningful context for the action. In the screenreader links list, you don't get that context at all - just three links that say "Export". 

The Download section above is it a bit better in that the link text itself disambiguates when there is more than one format, but it doesn't indicate the action, only the format.

For consistent visual layout and unique link text, I propose this:

<img width="269" alt="Screen Shot 2020-06-15 at 5 49 49 PM" src="https://user-images.githubusercontent.com/6945691/84719637-b8af2b00-af30-11ea-9556-56fe12b5a4ca.png">

with `sr-only` text added to the link to clarify the action:

`<a ...><span class="sr-only">Export </span>Shapefile</a>`

and the same pattern for the download options.

**Comment by cbeer** [comment]
Related to #646?

**Comment by jvine** [comment]
Ah, missed that one! Yes, that works. I'm going to close this one.
