### ISSUE TITLE
Move show tools (bookmark, cite, email) to show page header

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/earthworks#673]
See https://github.com/projectblacklight/blacklight/issues/2316 for the recommendation to move the core Blacklight tools (bookmark, cite, email, etc.) out of the sidebar. If this is done, the Earthworks sidebar can be focused on the geo-specific tools in one sidebar box, and use another for the Relations stuff, etc.

**Comment by thatbudakguy** [comment]
![Screenshot 2024-08-14 at 10 08 24](https://github.com/user-attachments/assets/c70f7972-a2aa-4088-94cf-d3b92433aca9)

**Comment by dnoneill** [comment]
Should be an easy update to the catalog controller with the merge of https://github.com/projectblacklight/blacklight/pull/3277
