### ISSUE TITLE
"Browse all records" link not retuning child records

### ISSUE THREAD

**Issue by kimdurante** [sul-dlss/earthworks#794]
Selecting "Browse all # records ..." from the list of Collection Items in EarthWorks results in an empty search.

Example "Browse all 15 records ... ":
https://earthworks.stanford.edu/catalog/stanford-gr373kr7662

This is true for all collection records.

**Comment by caaster** [comment]
Hi @kimdurante - tell us more about how this is impacting your work and/or the user experience. It would be good to understand the priority of this issue for us to fix. Thanks.

**Comment by cbeer** [comment]
I think this is https://github.com/geoblacklight/geoblacklight/pull/990, but the fix was not applied to earthworks 🤷

**Comment by kimdurante** [comment]
Hi @caaster. An end user would not be able to view/download all items in a collection which is the expected behavior of this link. Stace reported it to me when assisting a user this afternoon. We were able to access the items through SearchWorks, so it is not impeding any work. Thanks.
