### ISSUE TITLE
Surface "Availability" of a layer in the UI for search results

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/earthworks#8]

**Comment by drh-stanford** [comment]
Test to see whether we can update a single field in the index... and if so, write a tool to take a stream of (id, availabilty score) from geomontior.

**Comment by drh-stanford** [comment]
Initial integration is to do a one-shot index of the layer availiabilty score with static data from GeoMonitor

**Comment by drh-stanford** [comment]
I'm updating stage and prod with the new Solr field. Some test cases are:

*  `harvard-tg95utaircupy` which yields 0
* `harvard-glb-co-usa` which yields 0.43
* `harvard-am-ams-na3301l` which yields 1
* `harvard-archbouln` which has no availability score.

**Comment by mejackreed** [comment]
:+1: awesome thanks!

**Comment by drh-stanford** [comment]
We want to hold off on an "Availability" facet and instead improve the Access notion to include broken links. The semantics of "Availiability" as a solo facet are too confusing.
