### ISSUE TITLE
Add use and copyright information to metadata show page

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#81]
Examples: 

Restricted via GIS Restricted APO: http://purl.stanford.edu/vv853br8653
Restricted via Maps of Africa APO: http://purl.stanford.edu/jc604kx9499
Public via GIS Public Domain APO: http://purl.stanford.edu/cz128vq0535

**Comment by drh-stanford** [comment]
Turns out we have 3 APOs in our current corpus, so we'll need to parse the APOs to get the text, or something cleaner...

**Comment by mejackreed** [comment]
I think we need to have something in the Solr document that specifies which APO to use. Since "Public" / "Restricted" isn't enough.

**Comment by mejackreed** [comment]
So one thing also to note here is I don't think we need to actually add the copyright. Maybe we can get clarification? But we do not show copyright in SearchWorks only Use and Reproduction. @jvine can you comment on that?

**Comment by drh-stanford** [comment]
@kimdurante hey Kim... Tom wanted to add the Use and Reproduction language to the Earthworks metadata, but the examples I've found use the DC `rights` field for this. Is there another field that makes sense for the use and reproduction language as we're already using the `rights` field for "Public" vs. "Restricted"... if not, do you have any suggestions on how we might put both into the `rights` field?

See http://www.alastore.ala.org/nealschuman/companionwebsite/metadata-digital-collections/MDC_DC-MODS_Element_Comparison_Examples.pdf

**Comment by drh-stanford** [comment]
This issue was born out of the demo meeting from Tom's comments. That's where I got both use and copyright. I might have transcribed it wrong so we should get some clarification.

**Comment by kimdurante** [comment]
Hey...One way to handle this might be to use DC rights field for the use and reproduction statement and use  'dct:accessRights' for expressing public vs. restricted. If you need a unique rights field to govern access functionality in Earthworks that would probably be the best approach.
See: http://dublincore.org/documents/dcmi-terms/#terms-accessRights
'rights' is sometimes a more general permission statement,  'accessRights' applies specifically to policies. 

If you don't need a unique field to designate public/restricted and don't want to modify the geoBL  schema, we could probably concatenate the two fields from the access policy. 

Example:
"Restricted: These data are licensed by Stanford Libraries and are available to Stanford University affiliates only. Affiliates are limited to current faculty, staff and students. These data may not be reproduced or used for any purpose without permission. For more information please contact brannerlibrary@stanford.edu."

**Comment by mejackreed** [comment]
It feels like to me that `accessRights` might be the more appropriate field to handle Public/Restricted. This might be troublesome in changing in GeoBlacklight schema but it feels right for the longterm.

**Comment by jvine** [comment]
@mejackreed I don't think we explicitly excluded copyright in SW, I'm pretty sure we just show what's in the MODS via the display gem.

**Comment by mejackreed** [comment]
@kimdurante Is there a field in DC that makes sense for the copyright statement? `license` ? Thats where we put it with mods.

**Comment by drh-stanford** [comment]
Unfortunately the PURL application uses `rightsMetadata` datastream to extract the use and reproduction statement: http://purl.stanford.edu/vv853br8653.mods so if we wanted to forgo the schema change we could parse the http://purl.stanford.edu/vv853br8653.xml to extract the `rightsMetadata` language. If we want to change the schema, the `generate-geoblacklight` robot could do the `rightsMetadata` extraction and it's just a matter of picking the semantics for DC. I'd rather not stuff both Public/Restricted and the use/reproduction language in `rights` together, although that may be the simplest change. 

Anyway I'm inclined to use `accessRights` for the Public/Restricted and `rights` for the use/reproduction language.

Here's the definitions:

accessRights: Information about who can access the resource or an indication of its security status. Access Rights may include information regarding access or restrictions based on privacy, security, or other policies.

license: A legal document giving official permission to do something with the resource.

rights: Information about rights held in and over the resource. Typically, rights information includes a statement about various property rights associated with the resource, including intellectual property rights.

**Comment by kimdurante** [comment]
@mejackreed as @drh-stanford said license is usually a reference or link to the document itself. With GIS data, these are usually large contracts so they're not recorded this way. It looks like DC does not explicitly put copyright into its own distinct field so copyright might be ok to use as a form of license.

Some other APOs use licenses - such as the research data. So that might need to be displayed in place of copyright. We have not dealt with a GIS object that had use, license, and copyright statements.
The other choice would be to concatenate it with the use statement in the DC rights field if the distinction is not that important in EW since the PURL page also provides this.

**Comment by drh-stanford** [comment]
From 1/16 meeting, we need to include use & reproduction, license, and copyright from the PURL page onto the EarthWorks landing page.
