### ISSUE TITLE
Investigate Click-path for someone looking for the original TIFF/JP2 for a georeferenced map

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/earthworks#82]

**Comment by mejackreed** [comment]
Currently no prod data that has this.

**Comment by thatbudakguy** [comment]
plenty of prod data that has this now, but you still can't easily download .jp2s from the sul-embed viewer or PURL, it seems like.

**Comment by dnoneill** [comment]
Do we still need this since there is a path in sul-embed?

**Comment by thatbudakguy** [comment]
We need to check if you can still get it for things that aren't stanford, and thus aren't using sul-embed

**Comment by dnoneill** [comment]
Looks like all have a download original jpeg
Minnesota: https://earthworks.stanford.edu/catalog/p16022coll247:310
Indiana: https://earthworks.stanford.edu/catalog/VAC3073-M-00794 \
Rutgers: https://earthworks.stanford.edu/catalog/rutgers-lib:29184

**Comment by thatbudakguy** [comment]
I think the issue is that we don't want the jpg (which is a IIIF link) but the actual underlying JP2 that the image server is referencing. Although "why" is a good question...

**Comment by thatbudakguy** [comment]
Seems like for non-Stanford stuff people would need to include their own special key in `dct_references_s` allowing the JP2 download, which we can't expect people to do. Since this is resolved for Stanford content by the usage of sul-embed, I'm going to close it.
