### ISSUE TITLE
Emailing records doesn't work

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/earthworks#831]
```
 ArgumentError: SMTP From address may not be blank: nil
```

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49895/faults/39953437)

**Comment by corylown** [comment]
### Progress Notes

As expected setting a default :from address fixes the email sending issue:

`ActionMailer::Base.default from: 'no-reply@earthworks.stanford.edu'`

However, after the form is submitted the browser tries to request `https://kurma-earthworks-stage.stanford.edu/catalog/uva-MLBS_2009:water/email` and this causes a routing error: 
```
ActionController::UrlGenerationError (No route matches {:action=>"show", :controller=>"catalog", :id=>nil}, missing required keys: [:id]):
```
 Working on the latter issue now.
