### ISSUE TITLE
Add IIIF Link & Logo to Scanned Map item pages

### ISSUE THREAD

**Issue by mapninja** [sul-dlss/earthworks#909]
`As a user of scanned maps, I would like to know when a scanned map resource in Earthworks is available through iiif.`

We are currently not displaying iiif branding associated with scanned  map images, in Earthworks. iiif link badges should be displayed with Earthworks Embed viewers, as with Searchworks Embed viewers. 

At bottom right of sul embed div to create parity in display/utility between:

https://earthworks.stanford.edu/catalog/stanford-zk523hh0189

and:

https://searchworks.stanford.edu/view/11923272

**Comment by thatbudakguy** [comment]
![Image](https://user-images.githubusercontent.com/4924494/204403753-d3b644ed-d88b-4d7d-b3b8-3faa90a40dbe.png)

**Comment by dnoneill** [comment]
Need to wait until we upgrade to the latest version of Geoblacklight.
