### ISSUE TITLE
Set zoom level on landing page maps so that only one world map is shown

### ISSUE THREAD

**Issue by mapninja** [sul-dlss/earthworks#911]
`As someone who cares about cartographic presentation, I would like the default map to display a single instance of the world, by default.` 

This drives me crazy:

![Image](https://user-images.githubusercontent.com/1517244/200905406-df343fdd-8526-483b-81cb-9730569c5a48.png)

in Leaflet JS, this would be fixed with:
`setMaxBounds`
and for animation:
`maxBoundsViscosity`

**Comment by thatbudakguy** [comment]
note that this also applies to the map on the search page:

![Image](https://user-images.githubusercontent.com/4924494/204405240-e0acc6c2-bb0b-4ed3-a5bf-44a0c1d7c313.png)

big ten geoportal seems to address this by changing the background color to match the water:

![Image](https://user-images.githubusercontent.com/4924494/204405285-afb352f5-dd64-4191-8254-6bd3f20ba791.png)

**Comment by thatbudakguy** [comment]
Recent upgrades seem to have brought this back.

**Comment by mapninja** [comment]
![image](https://github.com/user-attachments/assets/c537149b-3a0f-43a0-b73c-be23dd39bbcc)

**Comment by dnoneill** [comment]
99% sure this needs to wait on Nick's importmap branch on geoblacklight.

**Comment by hudajkhan** [comment]
I think this can be closed with the merge but I will leave it to @dnoneill to check.
