### ISSUE TITLE
Add "Open in ArcGIS.com" Button

### ISSUE THREAD

**Issue by mapninja** [sul-dlss/earthworks#912]
`As a researcher using spatial data, I want to open the dataset I have found in Earthworks, directly in stanford.maps.arcgis.com, so that I can begin using it. `

Or, perhaps, "Send to ArcGIS.com"

Similar in spirit to Open in CARTO, but our relationship with Esri is more stable. Our Esri site license is considered infrastructure, so will never go away. This would create the ability to add WFS/WMS sources, directly to ArcGIS Online, where we currently have 2000+ users. 

Possibly can be done through the APIs? 

https://developers.arcgis.com/documentation/mapping-apis-and-services/data-hosting/data-publishing/#fn:support-table-1:2

We can call on Esri for collaboration with their developers on this.

**Comment by thatbudakguy** [comment]
per @dmede — this is only useful if we can link directly to the _specific_ dataset the user is viewing, which currently isn't possible for e.g. web services links. need investigate how the arcGIS.com API works and what types of values we can send over before we start to implement this.

**Comment by dnoneill** [comment]
I am not quite sure what to do here. We already have an open in arcgis button in earthworks that shows up if the data has an arcgis_urls. I think we might want to update our settings.yml to point to standard's version (ARCGIS_BASE_URL: "https://stanford.maps.arcgis.com/home/webmap/viewer.html") but other than that I am not sure what there is to do. If we are talking about users being able to load datasets into arcgis and us not publishing everything there I think this would be a part of the code snippets work? Moving back to ready in case someone else can figure this out.

**Comment by thatbudakguy** [comment]
Closing since current feedback seems to be that this isn't actually needed
