### ISSUE TITLE
Implement IIIF navPlace for any image with coordinate location or bounding box

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#923]
`As someone interested in developing map applications with iiif content, I would like to see the navPlace extension adopted by SUL, for all collections with bounding box metadata associated with items.`

the navPlace Extension Spec:
https://iiif.io/api/extension/navplace/ 

Enable structured use of spatial metadata associated with collections in interadtive applications:

## Examples of navPlace viewers:
https://mikeapp.github.io/maptime-demo/

https://centerfordigitalhumanities.github.io/navplace-viewer/?iiif-content=https://centerfordigitalhumanities.github.io/navplace-viewer/tests/fixtures/collection-2.json

https://eliotjordan.github.io/navplace/

**Comment by thatbudakguy** [comment]
duplicate of #919

**Comment by mapninja** [comment]
Here is an example of the utility of leveraging location for catalog records: Harvard's experiments with GeoHOLLIS  https://www.youtube.com/watch?v=ULkZE8TVP3I
