### ISSUE TITLE
Discrepancy in searchable layers

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/earthworks#965]
After indexing into staging using fresh OGM data and newer versions of GeoCombine (`rake earthworks:geocombine:clone` & `rake earthworks:geocombine:index`), the indexer reports that roughly 95,000 docs were indexed — close to the same as current production. Yet, running a blank search in staging returns only about 76,000 total results.

Some institutions (or at least UVa) are missing from the search results entirely. In solr, the total result count shows about 95,000, but I can't find any records from UVa. Where are these records, and what accounts for the discrepancy in the total result count?

**Comment by hudajkhan** [comment]
When looking at the logs, the query that is executed includes the following filter query: "fq"=>["-suppressed_b: true"].  This means the records that the interface should only show the records where "suppressed_b" is not true.  When I execute this filter query on Solr, I get 76,111 records which matches the number on the EarthWorks stage webapp blank/default search. 

This is an example of a suppressed record: https://earthworks-stage-a.stanford.edu/catalog/princeton-1c18dk604 .  If I search for this catalog id "princeton-1c18dk604", no results are returned through the interface.  When I searched for a catalog id belonging to a record which does not have "suppressed_b" set to true, I found the result. 

For reference, here is the full blank search Solr query from the logs:
Solr query: get select {"qt"=>nil, "start"=>0, "rows"=>10, "q.alt"=>"*:*", "facet"=>true, "facet.field"=>["dct_provenance_s", "dc_creator_sm", "dc_publisher_s", "dc_subject_sm", "dct_spatial_sm", "dc_source_sm", "solr_year_i", "dc_rights_s", "layer_geom_type_s", "dc_format_s"], "f.dct_provenance_s.facet.limit"=>9, "f.dc_creator_sm.facet.limit"=>7, "f.dc_publisher_s.facet.limit"=>7, "f.dc_subject_sm.facet.limit"=>7, "f.dct_spatial_sm.facet.limit"=>7, "f.solr_year_i.facet.limit"=>11, "facet.query"=>["dc_rights_s:Restricted", "dc_rights_s:Public", "(layer_availability_score_f:[0.2 TO 1])", "layer_availability_score_f:[0 TO 0.2]", "solr_year_i:[1 TO 199]", "solr_year_i:[200 TO 399]", "solr_year_i:[400 TO 599]", "solr_year_i:[600 TO 799]", "solr_year_i:[800 TO 999]", "solr_year_i:[1000 TO 1199]", "solr_year_i:[1200 TO 1399]", "solr_year_i:[1400 TO 1599]", "solr_year_i:[1600 TO 1799]", "solr_year_i:[1800 TO 1999]", "solr_year_i:[2000 TO 2016]"], "f.layer_geom_type_s.facet.limit"=>9, "f.dc_format_s.facet.limit"=>4, "sort"=>"score desc, dc_title_sort asc", "stats"=>"true", "stats.field"=>["solr_year_i"], "fq"=>["-suppressed_b: true"]}

**Comment by thatbudakguy** [comment]
Closing since this isn't a bug! Thanks for the investigation @hudajkhan.

The missing UVa records were because they don't specify a `geoblacklight_version` (the records use schema version 0.5, which didn't have this field) so the indexer skips them. https://github.com/OpenGeoMetadata/GeoCombine/pull/152 ensure swe no longer harvest archived repositories, which fixes that.
